import tables
var gNetvars* {.compileTime.} = initTable[string, uint]()
static:
  gNetvars["DT_SpriteTrail=>m_flMinFadeLength"] = 4232
  gNetvars["DT_BaseCSGrenade=>m_flThrowStrength"] = 13276
  gNetvars["DT_SpotlightEnd=>m_Radius"] = 2524
  gNetvars["DT_WeaponTablet=>m_flBootTime"] = 13472
  gNetvars["DT_SmokeStack=>m_DirLight.m_vPos"] = 2896
  gNetvars["DT_PropVehicleDriveable=>m_bExitAnimOn"] = 10689
  gNetvars["DT_BasePlayer=>m_bCameraManXRay"] = 13181
  gNetvars["DT_BasePlayer=>m_hViewModel"] = 0
  gNetvars["DT_CSPlayerResource=>m_szCrosshairCodes"] = 21029
  gNetvars["DT_LightGlow=>m_nOuterMaxDist"] = 2536
  gNetvars["DT_DustTrail=>m_Color"] = 2760
  gNetvars["DT_PropVehicleChoreoGeneric=>m_hPlayer"] = 10740
  gNetvars["DT_TEBubbles=>m_vecMaxs"] = 28
  gNetvars["DT_CSGameRulesProxy=>m_GGProgressiveWeaponKillUpgradeOrderT"] = 860
  gNetvars["DT_SmokeTrail=>m_MaxSpeed"] = 2800
  gNetvars["DT_CSPlayer=>m_nNumFastDucks"] = 41876
  gNetvars["DT_BasePlayer=>m_bShouldDrawPlayerWhileUsingViewEntity"] = 13120
  gNetvars["DT_WeaponTablet=>m_vecLocalHexFlags[0]"] = 13288
  gNetvars["DT_CSGameRulesProxy=>m_flTerroristTimeOutRemaining"] = 48
  gNetvars["DT_SporeTrail=>m_flStartSize"] = 2772
  gNetvars["DT_BaseEntity=>m_fadeMinDist"] = 756
  gNetvars["DT_EnvProjectedTexture=>m_iStyle"] = 2860
  gNetvars["DT_TEGlowSprite=>m_fScale"] = 32
  gNetvars["DT_SmokeStack=>m_iMaterialModel"] = 2952
  gNetvars["DT_BaseWeaponWorldModel=>m_fEffects"] = 240
  gNetvars["DT_CSGameRulesProxy=>m_szTournamentPredictionsTxt"] = 1904
  gNetvars["DT_TEClientProjectile=>m_vecOrigin"] = 16
  gNetvars["DT_TEMetalSparks=>m_vecPos"] = 16
  gNetvars["DT_EnvAmbientLight=>m_vecColor"] = 2816
  gNetvars["DT_CSPlayerResource=>m_iCompetitiveWins"] = 7048
  gNetvars["DT_CSPlayer=>m_flAutoMoveTargetTime"] = 15036
  gNetvars["DT_SceneEntity=>m_hActorList"] = 0
  gNetvars["DT_CSPlayer=>m_iDirection"] = 41868
  gNetvars["DT_DynamicLight=>m_OuterAngle"] = 2536
  gNetvars["DT_TEPlayerDecal=>m_nHitbox"] = 60
  gNetvars["DT_SunlightShadowControl=>m_flSunDistance"] = 2824
  gNetvars["DT_BaseViewModel=>m_nSkin"] = 2588
  gNetvars["DT_CSPlayerResource=>m_bHasDefuser"] = 6136
  gNetvars["DT_TEBubbleTrail=>m_vecMaxs"] = 28
  gNetvars["DT_FEPlayerDecal=>m_nUniqueID"] = 2520
  gNetvars["DT_TEBloodSprite=>b"] = 48
  gNetvars["DT_BasePlayer=>m_skybox3d.origin"] = 12532
  gNetvars["DT_SpatialEntity=>m_bEnabled"] = 2804
  gNetvars["DT_CHostage=>m_iHealth"] = 256
  gNetvars["DT_TEEffectDispatch=>m_fFlags"] = 64
  gNetvars["DT_StatueProp=>m_vShatterPosition"] = 10700
  gNetvars["DT_BasePlayer=>m_bWearingSuit"] = 12366
  gNetvars["DT_StatueProp=>m_vShatterForce"] = 10712
  gNetvars["DT_Func_LOD=>m_nDisappearMinDist"] = 2520
  gNetvars["DT_TEDecal=>m_nEntity"] = 40
  gNetvars["DT_Team=>m_scoreOvertime"] = 2892
  gNetvars["DT_BaseAttributableItem=>m_Attributes"] = 608
  gNetvars["DT_BasePlayer=>m_audio.soundscapeIndex"] = 12728
  gNetvars["DT_EnvDOFController=>m_flNearFocusDepth"] = 2528
  gNetvars["DT_BaseCombatWeapon=>m_iWeaponModule"] = 12876
  gNetvars["DT_Ragdoll=>m_ragPos"] = 0
  gNetvars["DT_Plasma=>m_nFlags"] = 2532
  gNetvars["DT_EnvTonemapController=>m_flCustomAutoExposureMin"] = 2524
  gNetvars["DT_PropVehicleDriveable=>m_nRPM"] = 10636
  gNetvars["DT_RocketTrail=>m_EndColor"] = 2772
  gNetvars["DT_BasePlayer=>m_iDeathPostEffect"] = 13172
  gNetvars["DT_BaseEntity=>m_flFadeScale"] = 764
  gNetvars["DT_RopeKeyframe=>m_iRopeMaterialModelIndex"] = 2580
  gNetvars["DT_BaseEntity=>m_iParentAttachment"] = 748
  gNetvars["DT_RopeKeyframe=>m_vecOrigin"] = 312
  gNetvars["DT_TEImpact=>m_vecNormal"] = 28
  gNetvars["DT_EnvWind=>m_iInitialWindDir"] = 2628
  gNetvars["DT_Team=>m_scoreTotal"] = 2880
  gNetvars["DT_RocketTrail=>m_SpawnRadius"] = 2812
  gNetvars["DT_Plasma=>m_nPlasmaModelIndex2"] = 2540
  gNetvars["DT_BasePlayer=>m_flFOVRate"] = 12288
  gNetvars["DT_BaseAttributableItem=>m_szCustomName"] = 700
  gNetvars["DT_CascadeLight=>m_flMaxShadowDist"] = 2556
  gNetvars["DT_BasePlayer=>m_skybox3d.fog.colorPrimary"] = 12564
  gNetvars["DT_ColorCorrection=>m_flCurWeight"] = 2552
  gNetvars["DT_TEEffectDispatch=>m_nHitBox"] = 104
  gNetvars["DT_CSPlayer=>m_bHud_RadarHidden"] = 45995
  gNetvars["DT_EnvProjectedTexture=>m_flRotation"] = 2876
  gNetvars["DT_FogController=>m_fog.colorPrimaryLerpTo"] = 2544
  gNetvars["DT_FuncSmokeVolume=>m_ParticleDrawWidth"] = 3020
  gNetvars["DT_EntityParticleTrail=>m_flEndSize"] = 2772
  gNetvars["DT_VGuiScreen=>m_hPlayerOwner"] = 2664
  gNetvars["DT_EnvGasCanister=>m_vecOrigin[2]"] = 320
  gNetvars["DT_Ragdoll_Attached=>m_ragdollAttachedObjectIndex"] = 11444
  gNetvars["DT_PhysPropLootCrate=>m_bRenderInTablet"] = 10741
  gNetvars["DT_FuncOccluder=>m_bActive"] = 2524
  gNetvars["DT_TEDecal=>m_vecOrigin"] = 16
  gNetvars["DT_BasePlayer=>m_skybox3d.fog.blend"] = 12617
  gNetvars["DT_PhysicsPropMultiplayer=>m_fMass"] = 10696
  gNetvars["DT_TELargeFunnel=>m_nReversed"] = 32
  gNetvars["DT_PlayerResource=>m_iPendingTeam"] = 4156
  gNetvars["DT_Beam=>m_fStartFrame"] = 2656
  gNetvars["DT_CSPlayerResource=>m_iMatchStats_Damage_Total"] = 24864
  gNetvars["DT_WeaponCSBase=>m_fLastShotTime"] = 13224
  gNetvars["DT_BaseCombatCharacter=>bcc_nonlocaldata"] = 0
  gNetvars["DT_SceneEntity=>m_nSceneStringIndex"] = 2536
  gNetvars["DT_BasePlayer=>m_uCameraManGraphs"] = 13184
  gNetvars["DT_BaseTeamObjectiveResource=>m_iTeamBaseIcons"] = 4572
  gNetvars["DT_TEBreakModel=>m_nModelIndex"] = 68
  gNetvars["DT_TEBubbleTrail=>m_nModelIndex"] = 44
  gNetvars["DT_RagdollManager=>m_iCurrentMaxRagdollCount"] = 2520
  gNetvars["DT_RocketTrail=>m_bDamaged"] = 2829
  gNetvars["DT_TEWorldDecal=>m_vecOrigin"] = 16
  gNetvars["DT_CSPlayer=>m_unRoundStartEquipmentValue"] = 45874
  gNetvars["DT_CascadeLight=>m_bEnabled"] = 2544
  gNetvars["DT_ParticleSmokeGrenade=>m_flSpawnTime"] = 2772
  gNetvars["DT_WeaponTablet=>m_nLastPurchaseIndex"] = 13556
  gNetvars["DT_CHostage=>m_nHostageState"] = 12084
  gNetvars["DT_FuncAreaPortalWindow=>m_flTranslucencyLimit"] = 2528
  gNetvars["DT_CFish=>m_waterLevel"] = 10732
  gNetvars["DT_Func_Dust=>m_usSolidFlags"] = 832
  gNetvars["DT_MapVetoPickController=>m_nTeamWithFirstChoice"] = 2544
  gNetvars["DT_TEGlowSprite=>m_nModelIndex"] = 28
  gNetvars["DT_TeamplayRoundBasedRulesProxy=>m_bStopWatch"] = 228
  gNetvars["DT_EnvWind=>m_iWindSeed"] = 2528
  gNetvars["DT_BaseAnimating=>m_nMuzzleFlashParity"] = 2660
  gNetvars["DT_BaseBeam=>m_nHaloIndex"] = 20
  gNetvars["DT_CSGameRulesProxy=>m_GGProgressiveWeaponOrderCT"] = 140
  gNetvars["DT_Inferno=>m_fireYDelta"] = 2932
  gNetvars["DT_WeaponCSBase=>m_flRecoilIndex"] = 13124
  gNetvars["DT_SteamJet=>m_bFaceLeft"] = 2788
  gNetvars["DT_ColorCorrection=>m_vecOrigin"] = 2520
  gNetvars["DT_CSGameRulesProxy=>m_arrProhibitedItemIndices"] = 2244
  gNetvars["DT_MaterialModifyControl=>m_bWrap"] = 3304
  gNetvars["DT_TEBeamEntPoint=>m_nEndEntity"] = 80
  gNetvars["DT_BaseAttributableItem=>m_iEntityQuality"] = 556
  gNetvars["DT_Team=>m_iClanID"] = 2904
  gNetvars["DT_PlayerResource=>m_iKills"] = 3116
  gNetvars["DT_Func_Dust=>m_nModelIndex"] = 600
  gNetvars["DT_TEMetalSparks=>m_vecDir"] = 28
  gNetvars["DT_EnvScreenOverlay=>m_iszOverlayNames"] = 0
  gNetvars["DT_PhysicsPropMultiplayer=>m_iPhysicsMode"] = 10692
  gNetvars["DT_VGuiScreen=>m_nAttachmentIndex"] = 2564
  gNetvars["DT_TEBreakModel=>m_fTime"] = 76
  gNetvars["DT_TEBeamRing=>m_nEndEntity"] = 80
  gNetvars["DT_MolotovProjectile=>m_bIsIncGrenade"] = 10768
  gNetvars["DT_CSRagdoll=>m_vecForce"] = 9856
  gNetvars["DT_VoteController=>m_iActiveIssueIndex"] = 2532
  gNetvars["DT_PropVehicleChoreoGeneric=>m_vehicleView.flPitchCurveLinear"] = 10904
  gNetvars["DT_CSGameRulesProxy=>m_iMatchStats_PlayersAlive_T"] = 2728
  gNetvars["DT_EnvScreenOverlay=>m_iDesiredOverlay"] = 5116
  gNetvars["DT_ColorCorrection=>m_bEnabled"] = 2816
  gNetvars["DT_BaseTeamObjectiveResource=>m_bInMiniRound"] = 4828
  gNetvars["DT_TEFireBullets=>m_flRecoilIndex"] = 68
  gNetvars["DT_SunlightShadowControl=>m_flFOV"] = 2828
  gNetvars["DT_SpriteTrail=>m_flEndWidth"] = 4220
  gNetvars["DT_BaseBeam=>b"] = 60
  gNetvars["DT_TEPlayerAnimEvent=>m_iEvent"] = 20
  gNetvars["DT_BaseEntity=>m_vecSpecifiedSurroundingMaxs"] = 856
  gNetvars["DT_BaseAttributableItem=>m_iItemDefinitionIndex"] = 554
  gNetvars["DT_EconEntity=>m_nFallbackSeed"] = 12748
  gNetvars["DT_CSGameRulesProxy=>m_iRoundTime"] = 68
  gNetvars["DT_BreakableProp=>m_qPreferredPlayerCarryAngles"] = 10628
  gNetvars["DT_RocketTrail=>m_StartColor"] = 2760
  gNetvars["DT_DynamicLight=>m_SpotRadius"] = 2540
  gNetvars["DT_CSGameRulesProxy=>m_bPlayAllStepSoundsOnServer"] = 126
  gNetvars["DT_CSGameRulesProxy=>m_numGlobalGiftsGiven"] = 2200
  gNetvars["DT_TEBreakModel=>m_nFlags"] = 80
  gNetvars["DT_EnvGasCanister=>m_bLanded"] = 10624
  gNetvars["DT_EntityDissolve=>m_flFadeOutStart"] = 2528
  gNetvars["DT_DynamicProp=>m_clrGlow"] = 10697
  gNetvars["DT_CSPlayer=>m_bIsPlayerGhost"] = 14997
  gNetvars["DT_CSPlayerResource=>m_iCompetitiveRankType"] = 7308
  gNetvars["DT_BaseTrigger=>m_spawnflags"] = 712
  gNetvars["DT_CSPlayer=>m_unActiveQuestId"] = 45864
  gNetvars["DT_TEBeamEnts=>m_nStartEntity"] = 76
  gNetvars["DT_TEEffectDispatch=>m_vStart.y"] = 32
  gNetvars["DT_EnvGasCanister=>m_flHorizSpeed"] = 10756
  gNetvars["DT_BaseAnimating=>m_flPlaybackRate"] = 2584
  gNetvars["DT_EnvTonemapController=>m_flTonemapPercentTarget"] = 2548
  gNetvars["DT_RocketTrail=>m_MaxSpeed"] = 2800
  gNetvars["DT_BaseEntity=>m_vecMins"] = 808
  gNetvars["DT_FuncSmokeVolume=>m_vecSpecifiedSurroundingMins"] = 844
  gNetvars["DT_CSPlayerResource=>m_iScore"] = 6528
  gNetvars["DT_PropVehicleDriveable=>m_nScannerDisabledWeapons"] = 10652
  gNetvars["DT_BasePlayer=>m_skybox3d.fog.HDRColorScale"] = 12624
  gNetvars["DT_SmokeTrail=>m_StartColor"] = 2760
  gNetvars["DT_ShadowControl=>m_shadowColor"] = 2532
  gNetvars["DT_PhysicsPropMultiplayer=>m_collisionMins"] = 10700
  gNetvars["DT_TEFireBullets=>m_fSpread"] = 72
  gNetvars["DT_BasePlayer=>m_hGroundEntity"] = 336
  gNetvars["DT_TEEffectDispatch=>m_vNormal"] = 40
  gNetvars["DT_StatueProp=>m_nShatterFlags"] = 10696
  gNetvars["DT_WeaponTablet=>m_vecNotificationTimestamps[0]"] = 13524
  gNetvars["DT_CSPlayer=>m_bCanMoveDuringFreezePeriod"] = 14728
  gNetvars["DT_TEPlantBomb=>m_iPlayer"] = 16
  gNetvars["DT_BaseTeamObjectiveResource=>m_pszCapLayoutInHUD"] = 7404
  gNetvars["DT_PropVehicleDriveable=>m_nHasBoost"] = 10648
  gNetvars["DT_BaseAnimating=>m_nForceBone"] = 9868
  gNetvars["DT_CSGameRulesProxy=>m_bTerroristTimeOutActive"] = 44
  gNetvars["DT_EnvProjectedTexture=>m_SpotlightTextureName"] = 2584
  gNetvars["DT_BaseCombatWeapon=>m_flNextPrimaryAttack"] = 12856
  gNetvars["DT_BaseAttributableItem=>m_nFallbackSeed"] = 12748
  gNetvars["DT_Sprite=>m_flScaleTime"] = 2568
  gNetvars["DT_CSPlayerResource=>m_bControllingBot"] = 8156
  gNetvars["DT_CSPlayer=>m_iNumGunGameKillsWithCurrentWeapon"] = 14672
  gNetvars["DT_PlayerResource=>m_iTeam"] = 3896
  gNetvars["DT_WeaponC4=>m_bIsPlantingViaUse"] = 13306
  gNetvars["DT_BaseEntity=>m_bAlternateSorting"] = 2364
  gNetvars["DT_BaseEntity=>m_nMinCPULevel"] = 2440
  gNetvars["DT_Beam=>m_nRenderFX"] = 602
  gNetvars["DT_EnvTonemapController=>m_bUseCustomAutoExposureMax"] = 2521
  gNetvars["DT_BaseTeamObjectiveResource=>m_flLazyCapPerc"] = 2652
  gNetvars["DT_CSGameRulesProxy=>m_nGuardianModeSpecialWeaponNeeded"] = 2188
  gNetvars["DT_TEShatterSurface=>m_nSurfaceType"] = 80
  gNetvars["DT_SunlightShadowControl=>m_flNearZ"] = 2832
  gNetvars["DT_CSGameRulesProxy=>m_iHostagesRemaining"] = 108
  gNetvars["DT_FogController=>m_fog.farz"] = 2560
  gNetvars["DT_PlantedC4=>m_flDefuseLength"] = 10664
  gNetvars["DT_EconEntity=>m_bInitialized"] = 596
  gNetvars["DT_FuncRotating=>m_angRotation[1]"] = 304
  gNetvars["DT_CSGameRulesProxy=>m_bFreezePeriod"] = 32
  gNetvars["DT_CSPlayer=>m_angEyeAngles[1]"] = 45952
  gNetvars["DT_FuncSmokeVolume=>m_RotationSpeed"] = 3032
  gNetvars["DT_BaseCombatCharacter=>m_hActiveWeapon"] = 12024
  gNetvars["DT_CSGameRulesProxy=>m_timeUntilNextPhaseStarts"] = 92
  gNetvars["DT_ParticleSystem=>m_iControlPointParents"] = 3116
  gNetvars["DT_CSPlayer=>m_iPlayerState"] = 14636
  gNetvars["DT_World=>m_WorldMaxs"] = 2536
  gNetvars["DT_AI_BaseNPC=>m_iSpeedModRadius"] = 12060
  gNetvars["DT_TeamplayRoundBasedRulesProxy=>m_TeamRespawnWaveTimes"] = 232
  gNetvars["DT_MaterialModifyControl=>m_nModifyMode"] = 3336
  gNetvars["DT_BumpMineProjectile=>m_nParentBoneIndex"] = 10708
  gNetvars["DT_BaseTeamObjectiveResource=>m_iStopWatchTimer"] = 2524
  gNetvars["DT_EntityParticleTrail=>m_iMaterialName"] = 2752
  gNetvars["DT_CSPlayerResource=>m_bHostageAlive"] = 5756
  gNetvars["DT_BaseCombatWeapon=>m_iNumEmptyAttacks"] = 12880
  gNetvars["DT_PropVehicleChoreoGeneric=>m_vehicleView.bClampEyeAngles"] = 10896
  gNetvars["DT_TEFootprintDecal=>m_vecDirection"] = 28
  gNetvars["DT_CSPlayerResource=>m_iMatchStats_Objective_Total"] = 26164
  gNetvars["DT_BaseAttributableItem=>m_iItemIDHigh"] = 576
  gNetvars["DT_BasePlayer=>m_hObserverTarget"] = 13196
  gNetvars["DT_Sun=>m_nOverlayMaterial"] = 2904
  gNetvars["DT_CSGameRulesProxy=>m_bAnyHostageReached"] = 112
  gNetvars["DT_MovieDisplay=>m_bEnabled"] = 2520
  gNetvars["DT_WeaponTablet=>m_vecPlayerPositionHistory[0]"] = 13560
  gNetvars["DT_CSPlayerResource=>m_iMatchStats_HeadShotKills_Total"] = 25904
  gNetvars["DT_EconEntity=>m_flFallbackWear"] = 12752
  gNetvars["DT_BaseViewModel=>m_nSequence"] = 10428
  gNetvars["DT_ParticleSystem=>m_nStopType"] = 2524
  gNetvars["DT_TEPlayerDecal=>m_nPlayer"] = 16
  gNetvars["DT_PropVehicleDriveable=>m_flThrottle"] = 10640
  gNetvars["DT_Sun=>m_clrRender"] = 112
  gNetvars["DT_EnvGasCanister=>m_vecDirection"] = 10712
  gNetvars["DT_TEBloodStream=>b"] = 48
  gNetvars["DT_RopeKeyframe=>m_nSegments"] = 3240
  gNetvars["DT_BaseAnimating=>m_nSequence"] = 10428
  gNetvars["DT_CSGameRulesProxy=>cs_gamerules_data"] = 0
  gNetvars["DT_Func_Dust=>m_LifetimeMin"] = 2540
  gNetvars["DT_EntityDissolve=>m_nDissolveType"] = 2552
  gNetvars["DT_CSPlayerResource=>m_iHostageEntityIDs"] = 5780
  gNetvars["DT_LightGlow=>HDRColorScale"] = 0
  gNetvars["DT_ColorCorrection=>m_flFadeInDuration"] = 2540
  gNetvars["DT_CSPlayer=>m_unTotalRoundDamageDealt"] = 14684
  gNetvars["DT_BasePlayer=>m_nWaterLevel"] = 606
  gNetvars["DT_BaseEntity=>m_nSolidType"] = 834
  gNetvars["DT_SlideshowDisplay=>m_szDisplayText"] = 2521
  gNetvars["DT_CSPlayer=>m_bHasControlledBotThisRound"] = 47624
  gNetvars["DT_EconEntity=>m_iItemIDHigh"] = 576
  gNetvars["DT_CSPlayer=>m_hCarriedHostage"] = 41976
  gNetvars["DT_BaseCombatWeapon=>m_iWorldDroppedModelIndex"] = 12872
  gNetvars["DT_BaseAttributableItem=>m_AttributeManager"] = 11648
  gNetvars["DT_FEPlayerDecal=>m_vecNormal"] = 2572
  gNetvars["DT_RopeKeyframe=>m_iStartAttachment"] = 3252
  gNetvars["DT_ColorCorrection=>m_bMaster"] = 2817
  gNetvars["DT_SmokeStack=>m_AmbientLight.m_vColor"] = 2880
  gNetvars["DT_BaseEntity=>m_vecOrigin"] = 312
  gNetvars["DT_BaseTeamObjectiveResource=>m_iTimerToShowInHUD"] = 2520
  gNetvars["DT_PostProcessController=>m_flPostProcessParameters"] = 2520
  gNetvars["DT_BasePlayer=>m_flConstraintRadius"] = 13140
  gNetvars["DT_EnvProjectedTexture=>m_flAmbient"] = 2572
  gNetvars["DT_BaseCSGrenade=>m_bPinPulled"] = 13266
  gNetvars["DT_Beam=>m_nBeamFlags"] = 2552
  gNetvars["DT_BaseToggle=>m_vecFinalDest"] = 2540
  gNetvars["DT_BreakableProp=>m_bClientPhysics"] = 10640
  gNetvars["DT_DangerZone=>m_nDropOrder"] = 2548
  gNetvars["DT_PointCommentaryNode=>m_hViewPosition"] = 11420
  gNetvars["DT_PhysPropLootCrate=>m_iMaxHealth"] = 10744
  gNetvars["DT_BreakableSurface=>m_flPanelWidth"] = 2532
  gNetvars["DT_SmokeTrail=>m_MinSpeed"] = 2796
  gNetvars["DT_TEEffectDispatch=>m_EffectData"] = 16
  gNetvars["DT_BaseAnimatingOverlay=>m_AnimOverlay"] = 0
  gNetvars["DT_WeaponCSBase=>m_iOriginalTeamNumber"] = 13148
  gNetvars["DT_CSGameRulesProxy=>m_flDMBonusStartTime"] = 1108
  gNetvars["DT_EnvWind=>m_flMinGustDelay"] = 2552
  gNetvars["DT_TEExplosion=>m_fScale"] = 32
  gNetvars["DT_EnvProjectedTexture=>m_bLightWorld"] = 2539
  gNetvars["DT_BoneFollower=>m_modelIndex"] = 2520
  gNetvars["DT_BaseTeamObjectiveResource=>m_iCappingTeam"] = 7196
  gNetvars["DT_CSPlayer=>m_bDuckOverride"] = 41880
  gNetvars["DT_Team=>m_szTeamMatchStat"] = 2620
  gNetvars["DT_Beam=>m_fFadeLength"] = 2644
  gNetvars["DT_CSPlayer=>m_bIsRescuing"] = 14648
  gNetvars["DT_Sprite=>m_flSpriteScale"] = 2564
  gNetvars["DT_PropVehicleChoreoGeneric=>m_bEnterAnimOn"] = 10748
  gNetvars["DT_SpatialEntity=>m_flCurWeight"] = 2540
  gNetvars["DT_CSPlayer=>m_flLastExoJumpTime"] = 15040
  gNetvars["DT_WeaponMelee=>m_flThrowAt"] = 13264
  gNetvars["DT_FuncMoveLinear=>m_vecVelocity"] = 276
  gNetvars["DT_EnvProjectedTexture=>m_hTargetEntity"] = 2524
  gNetvars["DT_BaseCombatWeapon=>m_nNextThinkTick"] = 252
  gNetvars["DT_CSPlayer=>m_unFreezetimeEndEquipmentValue"] = 45876
  gNetvars["DT_PropVehicleChoreoGeneric=>m_vehicleView.flPitchCurveZero"] = 10900
  gNetvars["DT_LightGlow=>m_spawnflags"] = 2540
  gNetvars["DT_World=>m_flMinPropScreenSpaceWidth"] = 2560
  gNetvars["DT_FogController=>m_fog.enable"] = 2588
  gNetvars["DT_EntityDissolve=>m_flFadeInStart"] = 2544
  gNetvars["DT_BasePlayer=>m_flDuckSpeed"] = 12208
  gNetvars["DT_BaseCombatWeapon=>m_flNextSecondaryAttack"] = 12860
  gNetvars["DT_CSPlayer=>m_iMatchStats_KillReward"] = 42564
  gNetvars["DT_DustTrail=>m_MaxSpeed"] = 2792
  gNetvars["DT_BasePlayer=>m_audio.localSound[1]"] = 12644
  gNetvars["DT_CSGameRulesProxy=>m_flRestartRoundTime"] = 80
  gNetvars["DT_CSPlayerResource=>m_iCompetitiveRanking"] = 6788
  gNetvars["DT_Ragdoll=>m_ragPos[0]"] = 10624
  gNetvars["DT_PointCommentaryNode=>m_flStartTime"] = 10628
  gNetvars["DT_DustTrail=>m_ParticleLifetime"] = 2776
  gNetvars["DT_TEDynamicLight=>exponent"] = 44
  gNetvars["DT_CSGameRulesProxy=>m_bMatchWaitingForResume"] = 64
  gNetvars["DT_BreachChargeProjectile=>m_nParentBoneIndex"] = 10712
  gNetvars["DT_WorldVguiText=>m_szDisplayText"] = 2521
  gNetvars["DT_Beam=>m_fHaloScale"] = 2648
  gNetvars["DT_EnvTonemapController=>m_bUseCustomBloomScale"] = 2522
  gNetvars["DT_TEEffectDispatch=>m_nMaterial"] = 96
  gNetvars["DT_ParticleFire=>m_vDirection"] = 2776
  gNetvars["DT_MaterialModifyControl=>m_flFramerate"] = 3308
  gNetvars["DT_BreachChargeProjectile=>m_vecParentBonePos"] = 10716
  gNetvars["DT_CSPlayer=>m_bIsAssassinationTarget"] = 47608
  gNetvars["DT_FuncSmokeVolume=>m_Color2"] = 2760
  gNetvars["DT_Func_Dust=>m_nSurroundType"] = 842
  gNetvars["DT_FireSmoke=>m_nFlameModelIndex"] = 2536
  gNetvars["DT_BaseEntity=>m_nRenderMode"] = 603
  gNetvars["DT_RopeKeyframe=>m_nChangeCount"] = 3276
  gNetvars["DT_BaseAnimating=>m_bClientSideFrameReset"] = 9920
  gNetvars["DT_Beam=>m_nRenderMode"] = 603
  gNetvars["DT_AI_BaseNPC=>m_bPerformAvoidance"] = 12068
  gNetvars["DT_Ragdoll=>m_nOverlaySequence"] = 11400
  gNetvars["DT_SpotlightEnd=>m_flLightScale"] = 2520
  gNetvars["DT_FuncSmokeVolume=>m_vecSpecifiedSurroundingMaxs"] = 856
  gNetvars["DT_TEEffectDispatch=>entindex"] = 16
  gNetvars["DT_CSPlayer=>m_flFlashMaxAlpha"] = 42012
  gNetvars["DT_Ragdoll=>m_hUnragdoll"] = 11388
  gNetvars["DT_CHostage=>m_lifeState"] = 607
  gNetvars["DT_Plasma=>m_flStartScale"] = 2520
  gNetvars["DT_CSGameRulesProxy=>m_bLogoMap"] = 125
  gNetvars["DT_BasePlayer=>m_flStepSize"] = 12316
  gNetvars["DT_WeaponC4=>m_bBombPlacedAnimation"] = 13304
  gNetvars["DT_QuadraticBeam=>m_controlPosition"] = 2532
  gNetvars["DT_CSGameRulesProxy=>m_nOvertimePlaying"] = 104
  gNetvars["DT_CSPlayerResource=>m_iMatchStats_EquipmentValue_Total"] = 25124
  gNetvars["DT_TEFizz=>m_nDensity"] = 24
  gNetvars["DT_EnvParticleScript=>m_flSequenceScale"] = 10852
  gNetvars["DT_TESpriteSpray=>m_vecDirection"] = 28
  gNetvars["DT_TEDecal=>m_nIndex"] = 48
  gNetvars["DT_TEBeamRingPoint=>m_vecCenter"] = 76
  gNetvars["DT_DustTrail=>m_StopEmitTime"] = 2784
  gNetvars["DT_MovieDisplay=>m_flUMin"] = 2784
  gNetvars["DT_LightGlow=>m_nVerticalSize"] = 2524
  gNetvars["DT_TEBeamSpline=>m_nPoints"] = 208
  gNetvars["DT_BaseTeamObjectiveResource=>m_iOwner"] = 7268
  gNetvars["DT_WeaponC4=>m_bShowC4LED"] = 13305
  gNetvars["DT_CSPlayer=>m_isCurrentGunGameLeader"] = 14729
  gNetvars["DT_BasePlayer=>m_bInDuckJump"] = 12364
  gNetvars["DT_ParticleSystem=>m_fEffects"] = 240
  gNetvars["DT_BaseBeam=>a"] = 64
  gNetvars["DT_WeaponCSBase=>m_hPrevOwner"] = 13188
  gNetvars["DT_SmokeTrail=>m_StopEmitTime"] = 2792
  gNetvars["DT_Func_Dust=>m_triggerBloat"] = 835
  gNetvars["DT_RocketTrail=>m_SpawnRate"] = 2756
  gNetvars["DT_Dronegun=>m_vecTargetOffset"] = 10636
  gNetvars["DT_RopeKeyframe=>m_RopeLength"] = 3260
  gNetvars["DT_EnvGasCanister=>m_vecStartPosition"] = 10688
  gNetvars["DT_PointWorldText=>m_flTextSize"] = 2828
  gNetvars["DT_CSPlayer=>m_bGunGameImmunity"] = 14660
  gNetvars["DT_BaseTeamObjectiveResource=>m_bControlPointsReset"] = 2537
  gNetvars["DT_SporeExplosion=>m_flEndSize"] = 2768
  gNetvars["DT_SmokeTrail=>m_EndSize"] = 2816
  gNetvars["DT_WeaponCSBaseGun=>m_iBurstShotsRemaining"] = 13268
  gNetvars["DT_SteamJet=>m_EndSize"] = 2768
  gNetvars["DT_Drone=>m_vecTagPositions"] = 0
  gNetvars["DT_ParticleSystem=>m_vServerControlPoints"] = 2796
  gNetvars["DT_Drone=>m_vecTagIncrements"] = 0
  gNetvars["DT_WaterLODControl=>m_flCheapWaterStartDistance"] = 2520
  gNetvars["DT_TeamplayRoundBasedRulesProxy=>m_flMapResetTime"] = 64
  gNetvars["DT_RocketTrail=>m_bEmit"] = 2828
  gNetvars["DT_SpriteTrail=>m_flTextureRes"] = 4228
  gNetvars["DT_BasePlayer=>m_bDrawViewmodel"] = 12365
  gNetvars["DT_BaseEntity=>m_bEligibleForScreenHighlight"] = 2489
  gNetvars["DT_BaseWeaponWorldModel=>m_nModelIndex"] = 600
  gNetvars["DT_CSPlayer=>m_bHasNightVision"] = 41882
  gNetvars["DT_DangerZone=>m_vecDangerZoneOriginStartedAt"] = 2520
  gNetvars["DT_FogController=>m_fog.startLerpTo"] = 2568
  gNetvars["DT_Sprite=>m_hAttachedToEntity"] = 2536
  gNetvars["DT_CSGameRulesProxy=>m_iPlayerSpawnHexIndices"] = 3352
  gNetvars["DT_WeaponCSBase=>m_iRecoilIndex"] = 13120
  gNetvars["DT_TEBubbleTrail=>m_vecMins"] = 16
  gNetvars["DT_TESprite=>m_vecOrigin"] = 16
  gNetvars["DT_BaseTeamObjectiveResource=>m_vCPPositions[0]"] = 2548
  gNetvars["DT_FuncSmokeVolume=>m_Color1"] = 2756
  gNetvars["DT_BasePlayer=>m_skybox3d.fog.start"] = 12580
  gNetvars["DT_CSGameRulesProxy=>m_iNumGunGameProgressiveWeaponsT"] = 132
  gNetvars["DT_CSPlayerResource=>m_iMatchStats_Kills_Total"] = 23304
  gNetvars["DT_CSGameRulesProxy=>m_bMapHasBombTarget"] = 113
  gNetvars["DT_WeaponTablet=>m_vecNearestMetalCratePos"] = 13480
  gNetvars["DT_BasePlayer=>m_vphysicsCollisionState"] = 12892
  gNetvars["DT_BaseEntity=>m_bIsAutoaimTarget"] = 96
  gNetvars["DT_AI_BaseNPC=>m_bSpeedModActive"] = 12071
  gNetvars["DT_LightGlow=>moveparent"] = 328
  gNetvars["DT_MovieDisplay=>m_bForcedSlave"] = 2779
  gNetvars["DT_PoseController=>m_fFModAmplitude"] = 2572
  gNetvars["DT_Prop_Hallucination=>m_fRechargeTime"] = 10656
  gNetvars["DT_Drone=>m_hCurrentPilot"] = 10728
  gNetvars["DT_TEEffectDispatch=>m_iEffectName"] = 116
  gNetvars["DT_PointCamera=>m_flFogMaxDensity"] = 2544
  gNetvars["DT_SpatialEntity=>m_vecOrigin"] = 2520
  gNetvars["DT_MovieDisplay=>m_bUseCustomUVs"] = 2780
  gNetvars["DT_Beam=>m_fAmplitude"] = 2652
  gNetvars["DT_Plasma=>m_nGlowModelIndex"] = 2544
  gNetvars["DT_CSGameRulesProxy=>m_flTabletHexOriginX"] = 3848
  gNetvars["DT_BasePlayer=>m_lifeState"] = 607
  gNetvars["DT_BaseEntity=>m_nSurroundType"] = 842
  gNetvars["DT_EnvGasCanister=>m_vecEnterWorldPosition"] = 10700
  gNetvars["DT_EnvGasCanister=>m_vecOrigin"] = 312
  gNetvars["DT_TEBeamPoints=>m_vecEndPoint"] = 88
  gNetvars["DT_SporeTrail=>m_flSpawnRadius"] = 2780
  gNetvars["DT_TEDecal=>m_nHitbox"] = 44
  gNetvars["DT_TEEffectDispatch=>m_vStart.x"] = 28
  gNetvars["DT_SporeExplosion=>m_flStartSize"] = 2764
  gNetvars["DT_CSGameRulesProxy=>m_fRoundStartTime"] = 76
  gNetvars["DT_CSGameRulesProxy=>m_bIsValveDS"] = 124
  gNetvars["DT_BeamSpotlight=>m_bSpotlightOn"] = 2532
  gNetvars["DT_FuncSmokeVolume=>m_nSolidType"] = 834
  gNetvars["DT_CSPlayer=>m_iMatchStats_Damage"] = 42204
  gNetvars["DT_SlideshowDisplay=>m_bEnabled"] = 2520
  gNetvars["DT_TEShatterSurface=>m_flHeight"] = 68
  gNetvars["DT_TEBloodSprite=>m_vecDirection"] = 28
  gNetvars["DT_BasePlayer=>m_iHealth"] = 256
  gNetvars["DT_BaseAnimating=>m_bSuppressAnimSounds"] = 10570
  gNetvars["DT_BaseAttributableItem=>m_OriginalOwnerXuidHigh"] = 12740
  gNetvars["DT_PlantedC4=>m_nBombSite"] = 10628
  gNetvars["DT_EnvWind=>m_iMaxWind"] = 2536
  gNetvars["DT_BaseTeamObjectiveResource=>m_vCPPositions"] = 0
  gNetvars["DT_Beam=>m_flHDRColorScale"] = 2524
  gNetvars["DT_BreakableSurface=>m_vCorner"] = 2552
  gNetvars["DT_Dronegun=>m_iHealth"] = 256
  gNetvars["DT_ColorCorrection=>m_maxFalloff"] = 2536
  gNetvars["DT_BaseAttributableItem=>m_OriginalOwnerXuidLow"] = 12736
  gNetvars["DT_BaseAttributableItem=>m_NetworkedDynamicAttributesForDemos"] = 672
  gNetvars["DT_FEPlayerDecal=>m_vecStart"] = 2548
  gNetvars["DT_RopeKeyframe=>m_Slack"] = 3264
  gNetvars["DT_EnvProjectedTexture=>m_bSimpleProjection"] = 2537
  gNetvars["DT_FogController=>m_fog.blend"] = 2589
  gNetvars["DT_Team=>m_bSurrendered"] = 2924
  gNetvars["DT_RopeKeyframe=>m_nMaxCPULevel"] = 2441
  gNetvars["DT_EntityFreezing=>m_bFinishFreezing"] = 2736
  gNetvars["DT_Beam=>m_nClipStyle"] = 2668
  gNetvars["DT_EntityDissolve=>m_flFadeOutModelLength"] = 2540
  gNetvars["DT_BasePlayer=>m_flLaggedMovementValue"] = 13716
  gNetvars["DT_CSPlayer=>m_vecSpawnRappellingRopeOrigin"] = 41904
  gNetvars["DT_WeaponTablet=>m_vecNotificationIds[0]"] = 13492
  gNetvars["DT_PointCamera=>m_FogColor"] = 2529
  gNetvars["DT_ItemAssaultSuitUseable=>m_nArmorValue"] = 13376
  gNetvars["DT_Plasma=>m_flScaleTime"] = 2528
  gNetvars["DT_Func_Dust=>m_flSizeMin"] = 2528
  gNetvars["DT_TEFireBullets=>m_iWeaponID"] = 52
  gNetvars["DT_ProxyToggle=>m_WithProxy"] = 2520
  gNetvars["DT_BaseEntity=>movecollide"] = 0
  gNetvars["DT_BaseWeaponWorldModel=>moveparent"] = 328
  gNetvars["DT_SteamJet=>m_bEmit"] = 2780
  gNetvars["DT_CSPlayer=>m_bKilledByTaser"] = 14721
  gNetvars["DT_BasePlayer=>m_audio.localSound[7]"] = 12716
  gNetvars["DT_CSGameRulesProxy=>m_nNextMapInMapgroup"] = 1120
  gNetvars["DT_TEPlayerAnimEvent=>m_hPlayer"] = 16
  gNetvars["DT_BaseBeam=>m_fWidth"] = 36
  gNetvars["DT_SlideshowDisplay=>m_bNoListRepeats"] = 2840
  gNetvars["DT_StatueProp=>m_hInitBaseAnimating"] = 10688
  gNetvars["DT_TeamplayRoundBasedRulesProxy=>m_bTeamReady"] = 196
  gNetvars["DT_BaseEntity=>m_iPendingTeamNum"] = 248
  gNetvars["DT_CSPlayer=>m_iShotsFired"] = 41872
  gNetvars["DT_PointCamera=>m_FOV"] = 2520
  gNetvars["DT_BasePlayer=>m_skybox3d.fog.dirPrimary"] = 12552
  gNetvars["DT_Ragdoll=>m_flBlendWeight"] = 11392
  gNetvars["DT_EnvWind=>m_iGustDirChange"] = 2564
  gNetvars["DT_SmokeStack=>m_bEmit"] = 2860
  gNetvars["DT_CSPlayer=>m_fMolotovDamageTime"] = 14692
  gNetvars["DT_MapVetoPickController=>m_nMapId1"] = 3340
  gNetvars["DT_CSGameRulesProxy=>m_flTabletHexSize"] = 3856
  gNetvars["DT_BasePlayer=>m_hColorCorrectionCtrl"] = 14252
  gNetvars["DT_RocketTrail=>m_MinSpeed"] = 2796
  gNetvars["DT_EnvTonemapController=>m_flBloomSaturation"] = 2544
  gNetvars["DT_RopeKeyframe=>m_iParentAttachment"] = 748
  gNetvars["DT_ParadropChopper=>m_vecOrigin[2]"] = 320
  gNetvars["DT_EnvTonemapController=>m_flTonemapPercentBrightPixels"] = 2552
  gNetvars["DT_FuncSmokeVolume=>m_vecMaxs"] = 820
  gNetvars["DT_CSPlayer=>m_nLastKillerIndex"] = 45996
  gNetvars["DT_MapVetoPickController=>m_nMapId4"] = 4108
  gNetvars["DT_Func_Dust=>m_vecSpecifiedSurroundingMins"] = 844
  gNetvars["DT_BasePlayer=>m_hViewModel[0]"] = 13048
  gNetvars["DT_CSGameRulesProxy=>m_bRoundInProgress"] = 5313
  gNetvars["DT_Dronegun=>m_bHasTarget"] = 10648
  gNetvars["DT_PoseController=>m_chPoseIndex"] = 2536
  gNetvars["DT_InfoMapRegion=>m_szLocToken"] = 2524
  gNetvars["DT_CSPlayerResource=>m_iMatchStats_Assists_Total"] = 23564
  gNetvars["DT_BasePlayer=>m_flFallVelocity"] = 12308
  gNetvars["DT_Team=>m_scoreSecondHalf"] = 2888
  gNetvars["DT_BaseEntity=>m_bAnimatedEveryTick"] = 2363
  gNetvars["DT_ItemAssaultSuitUseable=>m_bIsHeavyAssaultSuit"] = 13380
  gNetvars["DT_CSPlayer=>cslocaldata"] = 0
  gNetvars["DT_World=>m_bColdWorld"] = 2568
  gNetvars["DT_TEEffectDispatch=>m_nOtherEntIndex"] = 108
  gNetvars["DT_BreakableSurface=>m_RawPanelBitVec"] = 2604
  gNetvars["DT_CSPlayerResource=>m_bombsiteCenterB"] = 5744
  gNetvars["DT_WeaponTablet=>m_vecNotificationIds"] = 0
  gNetvars["DT_BaseAnimating=>m_hLightingOrigin"] = 10564
  gNetvars["DT_CSPlayer=>m_bHideTargetID"] = 47516
  gNetvars["DT_TEProjectedDecal=>m_angRotation"] = 28
  gNetvars["DT_MapVetoPickController=>m_nMapId3"] = 3852
  gNetvars["DT_BasePlayer=>m_vecBaseVelocity"] = 288
  gNetvars["DT_CSRagdoll=>m_nModelIndex"] = 600
  gNetvars["DT_EnvDOFController=>m_bDOFEnabled"] = 2520
  gNetvars["DT_Beam=>m_fSpeed"] = 2660
  gNetvars["DT_CSPlayer=>m_iSecondaryAddon"] = 41852
  gNetvars["DT_SlideshowDisplay=>m_chCurrentSlideLists"] = 2800
  gNetvars["DT_BaseAnimating=>m_vecForce"] = 9856
  gNetvars["DT_PlantedC4=>m_flC4Blow"] = 10640
  gNetvars["DT_BaseAnimating=>serveranimdata"] = 0
  gNetvars["DT_CSGameRulesProxy=>m_numBestOfMaps"] = 2460
  gNetvars["DT_CSPlayer=>m_nIsAutoMounting"] = 15000
  gNetvars["DT_RopeKeyframe=>m_Width"] = 3280
  gNetvars["DT_BaseGrenade=>m_flDamage"] = 10648
  gNetvars["DT_BaseAnimating=>m_flPoseParameter"] = 10100
  gNetvars["DT_TEBubbles=>m_fHeight"] = 40
  gNetvars["DT_CSPlayerResource=>m_iBotDifficulty"] = 17064
  gNetvars["DT_TeamplayRoundBasedRulesProxy=>m_flNextRespawnWave"] = 68
  gNetvars["DT_DangerZone=>m_iWave"] = 2552
  gNetvars["DT_RopeKeyframe=>m_TextureScale"] = 3268
  gNetvars["DT_TEEffectDispatch=>m_flScale"] = 76
  gNetvars["DT_TeamplayRoundBasedRulesProxy=>m_bInSetup"] = 45
  gNetvars["DT_World=>m_WorldMins"] = 2524
  gNetvars["DT_CSGameRulesProxy=>m_fWarmupPeriodEnd"] = 36
  gNetvars["DT_CSGameRulesProxy=>m_bCTCantBuy"] = 2481
  gNetvars["DT_CSPlayer=>m_iMatchStats_CashEarned"] = 43284
  gNetvars["DT_BaseCombatWeapon=>m_iClip2"] = 12904
  gNetvars["DT_Sun=>m_clrOverlay"] = 2872
  gNetvars["DT_CascadeLight=>m_LightColor"] = 2546
  gNetvars["DT_BasePlayer=>m_nNextThinkTick"] = 252
  gNetvars["DT_TEExplosion=>m_nMagnitude"] = 64
  gNetvars["DT_BasePlayer=>m_audio.localSound[2]"] = 12656
  gNetvars["DT_CSGameRulesProxy=>m_nGuardianModeSpecialKillsRemaining"] = 2184
  gNetvars["DT_CFish=>m_x"] = 10696
  gNetvars["DT_TEMuzzleFlash=>m_flScale"] = 40
  gNetvars["DT_BaseCombatWeapon=>m_iClip1"] = 12900
  gNetvars["DT_BaseBeam=>m_fEndWidth"] = 40
  gNetvars["DT_BaseTeamObjectiveResource=>m_flTeamCapTime"] = 3484
  gNetvars["DT_CSPlayer=>m_flDetectedByEnemySensorTime"] = 14712
  gNetvars["DT_FuncLadder=>m_vecLadderDir"] = 2520
  gNetvars["DT_BasePlayer=>m_bConstraintPastRadius"] = 13152
  gNetvars["DT_TEDust=>m_flSpeed"] = 32
  gNetvars["DT_TEPhysicsProp=>m_angRotation[1]"] = 32
  gNetvars["DT_SmokeTrail=>m_MaxDirectedSpeed"] = 2808
  gNetvars["DT_SmokeTrail=>m_nAttachment"] = 2840
  gNetvars["DT_TEEffectDispatch=>m_vOrigin.y"] = 20
  gNetvars["DT_RopeKeyframe=>m_iDefaultRopeMaterialModelIndex"] = 2584
  gNetvars["DT_CSGameRulesProxy=>m_unDMBonusWeaponLoadoutSlot"] = 1116
  gNetvars["DT_TEClientProjectile=>m_hOwner"] = 48
  gNetvars["DT_PropVehicleDriveable=>m_bUnableToFire"] = 10765
  gNetvars["DT_EntityFreezing=>m_flFrozenPerHitbox"] = 2532
  gNetvars["DT_BeamSpotlight=>m_bHasDynamicLight"] = 2533
  gNetvars["DT_WeaponM3=>m_reloadState"] = 13268
  gNetvars["DT_CSGameRulesProxy=>m_fMatchStartTime"] = 72
  gNetvars["DT_BaseViewModel=>m_nNewSequenceParity"] = 2628
  gNetvars["DT_CSGameRulesProxy=>m_flSurvivalStartTime"] = 5032
  gNetvars["DT_BaseCombatWeapon=>m_nViewModelIndex"] = 12852
  gNetvars["DT_BaseEntity=>m_triggerBloat"] = 835
  gNetvars["DT_InfoMapRegion=>m_flRadius"] = 2520
  gNetvars["DT_CSPlayer=>m_ArmorValue"] = 45944
  gNetvars["DT_DangerZoneController=>m_vecEndGameCircleEnd"] = 2536
  gNetvars["DT_BasePlayer=>m_skybox3d.area"] = 12544
  gNetvars["DT_TEPhysicsProp=>m_angRotation[0]"] = 28
  gNetvars["DT_ColorCorrectionVolume=>m_FadeDuration"] = 2600
  gNetvars["DT_CSPlayerResource=>m_iCashSpentThisRound"] = 19144
  gNetvars["DT_FuncSmokeVolume=>m_Collision"] = 800
  gNetvars["DT_BaseAttributableItem=>m_iEntityLevel"] = 560
  gNetvars["DT_CSGameRulesProxy=>m_nGuardianModeWaveNumber"] = 2180
  gNetvars["DT_CSPlayer=>m_vecAutomoveTargetEnd"] = 15016
  gNetvars["DT_EconEntity=>m_OriginalOwnerXuidHigh"] = 12740
  gNetvars["DT_PointCamera=>m_bActive"] = 2548
  gNetvars["DT_EconEntity=>m_ProviderType"] = 11684
  gNetvars["DT_BasePlayer=>m_nTickBase"] = 13360
  gNetvars["DT_ParticleSystem=>m_vecOrigin"] = 312
  gNetvars["DT_CHostage=>m_iMaxHealth"] = 12056
  gNetvars["DT_BasePlayer=>m_audio.localSound[0]"] = 12632
  gNetvars["DT_BaseViewModel=>m_nAnimationParity"] = 10692
  gNetvars["DT_BasePlayer=>m_audio.localBits"] = 12732
  gNetvars["DT_TEEffectDispatch=>m_vOrigin.x"] = 16
  gNetvars["DT_PointCommentaryNode=>m_iNodeNumberMax"] = 11412
  gNetvars["DT_CSGameRulesProxy=>m_numGlobalGifters"] = 2204
  gNetvars["DT_SlideshowDisplay=>m_fMinSlideTime"] = 2824
  gNetvars["DT_MaterialModifyControl=>m_szMaterialVar"] = 2775
  gNetvars["DT_FEPlayerDecal=>m_vecEndPos"] = 2536
  gNetvars["DT_WeaponTablet=>m_vecPlayerPositionHistory"] = 0
  gNetvars["DT_TEFireBullets=>m_iSoundType"] = 76
  gNetvars["DT_BeamSpotlight=>m_nHaloIndex"] = 2520
  gNetvars["DT_BaseCombatCharacter=>m_nRelativeDirectionOfLastInjury"] = 12032
  gNetvars["DT_ParticlePerformanceMonitor=>m_bMeasurePerf"] = 2521
  gNetvars["DT_RocketTrail=>m_ParticleLifetime"] = 2788
  gNetvars["DT_CSGameRulesProxy=>m_flGameStartTime"] = 88
  gNetvars["DT_PoseController=>m_bInterpolationWrap"] = 2552
  gNetvars["DT_DangerZone=>m_flBombLaunchTime"] = 2532
  gNetvars["DT_BaseEntity=>m_bSimulatedEveryTick"] = 2362
  gNetvars["DT_CSPlayer=>m_hRagdoll"] = 41964
  gNetvars["DT_WeaponSawedoff=>m_reloadState"] = 13268
  gNetvars["DT_PropVehicleChoreoGeneric=>m_vehicleView.flYawMin"] = 10920
  gNetvars["DT_EnvProjectedTexture=>m_bEnableShadows"] = 2536
  gNetvars["DT_EnvWind=>m_iMaxGust"] = 2548
  gNetvars["DT_CSRagdoll=>m_vecRagdollOrigin"] = 10764
  gNetvars["DT_TESparks=>m_vecDir"] = 36
  gNetvars["DT_BaseCombatWeapon=>m_iWorldModelIndex"] = 12868
  gNetvars["DT_SporeExplosion=>m_bDontRemove"] = 2781
  gNetvars["DT_CSGameRulesProxy=>m_nCTTimeOuts"] = 60
  gNetvars["DT_TEBloodSprite=>g"] = 44
  gNetvars["DT_CSPlayer=>m_iThrowGrenadeCounter"] = 14700
  gNetvars["DT_PropVehicleChoreoGeneric=>m_vehicleView.flPitchMin"] = 10928
  gNetvars["DT_Drone=>m_hPotentialCargo"] = 10724
  gNetvars["DT_BasePlayer=>m_fForceTeam"] = 13260
  gNetvars["DT_RocketTrail=>m_flFlareScale"] = 2848
  gNetvars["DT_WeaponTaser=>m_fFireTime"] = 13296
  gNetvars["DT_CSPlayer=>m_bIsDefusing"] = 14640
  gNetvars["DT_CHostage=>m_flGrabSuccessTime"] = 12092
  gNetvars["DT_BaseCombatWeapon=>m_iPrimaryAmmoType"] = 12892
  gNetvars["DT_TEBeamRingPoint=>m_flStartRadius"] = 88
  gNetvars["DT_BaseEntity=>m_hOwnerEntity"] = 332
  gNetvars["DT_PoseController=>m_fPoseValue"] = 2544
  gNetvars["DT_MaterialModifyControl=>m_flFloatLerpTransitionTime"] = 3324
  gNetvars["DT_Sun=>m_nSize"] = 2876
  gNetvars["DT_BasePlayer=>m_iFOV"] = 12772
  gNetvars["DT_TeamplayRoundBasedRulesProxy=>m_iRoundState"] = 40
  gNetvars["DT_WeaponCSBase=>m_flPostponeFireReadyTime"] = 13132
  gNetvars["DT_Ragdoll_Attached=>m_attachmentPointBoneSpace"] = 11408
  gNetvars["DT_CSRagdoll=>m_iDeathFrame"] = 10780
  gNetvars["DT_CSPlayer=>m_flStamina"] = 41864
  gNetvars["DT_CSPlayerResource=>m_iControlledPlayer"] = 8224
  gNetvars["DT_FuncLadder=>m_vecPlayerMountPositionBottom"] = 2564
  gNetvars["DT_TEEffectDispatch=>m_vAngles"] = 52
  gNetvars["DT_EnvProjectedTexture=>m_flNearZ"] = 2576
  gNetvars["DT_CSPlayer=>m_passiveItems"] = 45904
  gNetvars["DT_World=>m_flWaveHeight"] = 2520
  gNetvars["DT_MaterialModifyControl=>m_iFrameStart"] = 3296
  gNetvars["DT_BasePlayer=>m_vecVelocity[2]"] = 284
  gNetvars["DT_BaseBeam=>m_fLife"] = 32
  gNetvars["DT_BaseTeamObjectiveResource=>m_iszWarnSound[0]"] = 4868
  gNetvars["DT_Func_Dust=>m_vecMaxs"] = 820
  gNetvars["DT_Beam=>m_fWidth"] = 2636
  gNetvars["DT_EnvProjectedTexture=>m_flLightFOV"] = 2532
  gNetvars["DT_WeaponTablet=>m_vecLocalHexFlags"] = 0
  gNetvars["DT_CSGameRulesProxy=>m_bCTTimeOutActive"] = 45
  gNetvars["DT_BoneFollower=>m_solidIndex"] = 2524
  gNetvars["DT_EnvGasCanister=>m_flFlightSpeed"] = 10740
  gNetvars["DT_EnvProjectedTexture=>m_nSpotlightTextureFrame"] = 2852
  gNetvars["DT_ColorCorrectionVolume=>m_MaxWeight"] = 2596
  gNetvars["DT_BasePlayer=>m_flFriction"] = 324
  gNetvars["DT_TEClientProjectile=>m_nLifeTime"] = 44
  gNetvars["DT_Inferno=>m_bFireIsBurning"] = 3732
  gNetvars["DT_TEDynamicLight=>m_fTime"] = 48
  gNetvars["DT_SmokeTrail=>m_Opacity"] = 2784
  gNetvars["DT_CSPlayer=>m_fMolotovUseTime"] = 14688
  gNetvars["DT_DangerZoneController=>m_bDangerZoneControllerEnabled"] = 2520
  gNetvars["DT_SmokeStack=>m_DirLight.m_vColor"] = 2908
  gNetvars["DT_ParticleSystem=>moveparent"] = 328
  gNetvars["DT_BasePlayer=>m_vecViewOffset[0]"] = 264
  gNetvars["DT_DetailController=>m_flFadeEndDist"] = 2524
  gNetvars["DT_DynamicProp=>m_bUseHitboxesForRenderBox"] = 10660
  gNetvars["DT_TeamplayRoundBasedRulesProxy=>teamplayroundbased_gamerules_data"] = 0
  gNetvars["DT_BasePlayer=>m_bDucked"] = 12356
  gNetvars["DT_BasePlayer=>m_aimPunchAngleVel"] = 12344
  gNetvars["DT_TEDynamicLight=>g"] = 36
  gNetvars["DT_Sprite=>m_flHDRColorScale"] = 2580
  gNetvars["DT_SurvivalSpawnChopper=>m_vecOrigin"] = 312
  gNetvars["DT_FEPlayerDecal=>m_nHitbox"] = 2592
  gNetvars["DT_World=>m_flMaxPropScreenSpaceWidth"] = 2564
  gNetvars["DT_SmokeGrenadeProjectile=>m_nSmokeEffectTickBegin"] = 10768
  gNetvars["DT_SmokeTrail=>m_bEmit"] = 2836
  gNetvars["DT_ParticleFire=>m_vOrigin"] = 2764
  gNetvars["DT_CSRagdoll=>m_iDeathPose"] = 10776
  gNetvars["DT_TEShatterSurface=>m_vecAngles"] = 28
  gNetvars["DT_WeaponCSBase=>m_iIronSightMode"] = 13252
  gNetvars["DT_CSGameRulesProxy=>m_iActiveAssassinationTargetMissionID"] = 3104
  gNetvars["DT_BaseTrigger=>m_bClientSidePredicted"] = 2568
  gNetvars["DT_ShadowControl=>m_flShadowMaxDist"] = 2536
  gNetvars["DT_DynamicLight=>m_Flags"] = 2520
  gNetvars["DT_CHostage=>m_flDropStartTime"] = 12096
  gNetvars["DT_HandleTest=>m_bSendHandle"] = 2524
  gNetvars["DT_SlideshowDisplay=>m_iCycleType"] = 2836
  gNetvars["DT_BasePlayer=>m_hZoomOwner"] = 12876
  gNetvars["DT_EconEntity=>m_szCustomName"] = 700
  gNetvars["DT_FireSmoke=>m_flScaleTime"] = 2528
  gNetvars["DT_CSPlayer=>m_unMusicID"] = 45908
  gNetvars["DT_FogController=>m_fog.start"] = 2552
  gNetvars["DT_BaseAttributableItem=>m_bInitialized"] = 596
  gNetvars["DT_PropVehicleChoreoGeneric=>m_bExitAnimOn"] = 10749
  gNetvars["DT_TEPlantBomb=>m_vecOrigin"] = 20
  gNetvars["DT_Func_Dust=>m_SpeedMax"] = 2536
  gNetvars["DT_BasePlayer=>m_flDuckAmount"] = 12204
  gNetvars["DT_BaseDoor=>m_flWaveHeight"] = 2568
  gNetvars["DT_SmokeStack=>m_StartSize"] = 2844
  gNetvars["DT_MovieDisplay=>m_flUMax"] = 2788
  gNetvars["DT_Beam=>m_flFrame"] = 2664
  gNetvars["DT_TEGlowSprite=>m_fLife"] = 36
  gNetvars["DT_BasePlayer=>m_audio.localSound[3]"] = 12668
  gNetvars["DT_CSGameRulesProxy=>m_bBombPlanted"] = 2469
  gNetvars["DT_MovieDisplay=>m_flVMax"] = 2796
  gNetvars["DT_BaseFlex=>m_viewtarget"] = 10736
  gNetvars["DT_CSGameRulesProxy=>m_szTournamentEventStage"] = 1384
  gNetvars["DT_RopeKeyframe=>m_hStartPoint"] = 3244
  gNetvars["DT_TEPlayerDecal=>m_vecOrigin"] = 20
  gNetvars["DT_BaseCombatWeapon=>m_iViewModelIndex"] = 12864
  gNetvars["DT_EnvDOFController=>m_flFarBlurRadius"] = 2544
  gNetvars["DT_DetailController=>m_flFadeStartDist"] = 2520
  gNetvars["DT_DustTrail=>m_MinDirectedSpeed"] = 2796
  gNetvars["DT_HandleTest=>m_Handle"] = 2520
  gNetvars["DT_CSPlayer=>m_nLastConcurrentKilled"] = 46000
  gNetvars["DT_SmokeTrail=>m_SpawnRadius"] = 2820
  gNetvars["DT_ParticleSmokeGrenade=>m_CurrentStage"] = 2756
  gNetvars["DT_BaseEntity=>m_vecSpecifiedSurroundingMins"] = 844
  gNetvars["DT_TESpriteSpray=>m_vecOrigin"] = 16
  gNetvars["DT_PlayerPing=>m_hPlayer"] = 2532
  gNetvars["DT_TEDust=>m_flSize"] = 28
  gNetvars["DT_EconEntity=>m_Attributes"] = 608
  gNetvars["DT_BaseEntity=>AnimTimeMustBeFirst"] = 0
  gNetvars["DT_TEFireBullets=>m_vecOrigin"] = 24
  gNetvars["DT_CSPlayer=>m_iMatchStats_HeadShotKills"] = 43044
  gNetvars["DT_BaseCombatWeapon=>m_bFlipViewModel"] = 12996
  gNetvars["DT_TEEffectDispatch=>m_nSurfaceProp"] = 92
  gNetvars["DT_CHostage=>m_jumpedThisFrame"] = 12081
  gNetvars["DT_FogController=>m_fog.duration"] = 2584
  gNetvars["DT_Ragdoll=>m_ragAngles"] = 0
  gNetvars["DT_CFish=>m_poolOrigin"] = 10720
  gNetvars["DT_TEFireBullets=>m_iMode"] = 56
  gNetvars["DT_BasePlayer=>m_bCameraManOverview"] = 13182
  gNetvars["DT_BaseBeam=>m_nFlags"] = 72
  gNetvars["DT_FuncRotating=>m_flSimulationTime"] = 616
  gNetvars["DT_TEBloodStream=>m_nAmount"] = 56
  gNetvars["DT_PropVehicleChoreoGeneric=>m_bForceEyesToAttachment"] = 10764
  gNetvars["DT_Beam=>m_nAttachIndex"] = 2596
  gNetvars["DT_TEBreakModel=>m_nRandomization"] = 64
  gNetvars["DT_TriggerSoundOperator=>m_nSoundOperator"] = 2576
  gNetvars["DT_TEShatterSurface=>m_flWidth"] = 64
  gNetvars["DT_CSPlayer=>m_bIsControllingBot"] = 47609
  gNetvars["DT_RopeKeyframe=>m_fLockedPoints"] = 3272
  gNetvars["DT_CSPlayerResource=>m_iMatchStats_EnemiesFlashed_Total"] = 26944
  gNetvars["DT_EconEntity=>m_AttributeManager"] = 11648
  gNetvars["DT_CSPlayer=>m_flVelocityModifier"] = 41884
  gNetvars["DT_EntityFlame=>m_hEntAttached"] = 2520
  gNetvars["DT_EconEntity=>m_NetworkedDynamicAttributesForDemos"] = 672
  gNetvars["DT_DynamicLight=>m_InnerAngle"] = 2532
  gNetvars["DT_FEPlayerDecal=>m_nTintID"] = 2596
  gNetvars["DT_ParticleSystem=>m_iEffectIndex"] = 2520
  gNetvars["DT_Team=>m_szClanTeamname"] = 2572
  gNetvars["DT_WeaponTablet=>m_flUpgradeExpirationTime[0]"] = 13272
  gNetvars["DT_EnvGasCanister=>m_flFlightTime"] = 10736
  gNetvars["DT_SteamJet=>m_Rate"] = 2772
  gNetvars["DT_CSGameRulesProxy=>m_nEndMatchMapGroupVoteOptions"] = 3152
  gNetvars["DT_CSPlayer=>m_szArmsModel"] = 14731
  gNetvars["DT_BasePlayer=>m_skybox3d.fog.maxdensity"] = 12592
  gNetvars["DT_FuncRotating=>m_angRotation[2]"] = 308
  gNetvars["DT_BaseViewModel=>m_bShouldIgnoreOffsetAndAccuracy"] = 10640
  gNetvars["DT_TEPhysicsProp=>m_nModelIndex"] = 52
  gNetvars["DT_CSGameRulesProxy=>m_iFirstSecondHalfRound"] = 5316
  gNetvars["DT_EnvTonemapController=>m_flTonemapRate"] = 2560
  gNetvars["DT_TEBeamFollow=>m_iEntIndex"] = 76
  gNetvars["DT_CSPlayerResource=>m_iMatchStats_Deaths_Total"] = 23824
  gNetvars["DT_TEEffectDispatch=>m_vOrigin.z"] = 24
  gNetvars["DT_FogController=>m_fog.maxdensity"] = 2564
  gNetvars["DT_TEFizz=>m_nModelIndex"] = 20
  gNetvars["DT_TEClientProjectile=>m_nModelIndex"] = 40
  gNetvars["DT_RocketTrail=>m_EndSize"] = 2808
  gNetvars["DT_CSPlayer=>m_bPlayerDominatingMe"] = 46293
  gNetvars["DT_ColorCorrection=>m_flMaxWeight"] = 2548
  gNetvars["DT_Beam=>m_nModelIndex"] = 600
  gNetvars["DT_BaseAnimating=>m_bClientSideRagdoll"] = 633
  gNetvars["DT_PoseController=>m_fFModRate"] = 2568
  gNetvars["DT_TEEffectDispatch=>m_flRadius"] = 84
  gNetvars["DT_CSPlayer=>m_flLowerBodyYawTarget"] = 14992
  gNetvars["DT_WeaponCSBase=>m_flDoneSwitchingSilencer"] = 13140
  gNetvars["DT_CSPlayer=>m_flThirdpersonRecoil"] = 47512
  gNetvars["DT_TEShatterSurface=>m_uchBackColor[2]"] = 89
  gNetvars["DT_WeaponFists=>m_bPlayingUninterruptableAct"] = 13264
  gNetvars["DT_FuncRotating=>m_vecOrigin"] = 312
  gNetvars["DT_EnvGasCanister=>m_vecStartAngles"] = 10724
  gNetvars["DT_TEBeamPoints=>m_vecStartPoint"] = 76
  gNetvars["DT_TEBreakModel=>m_vecVelocity"] = 52
  gNetvars["DT_MapVetoPickController=>m_nMapId5"] = 4364
  gNetvars["DT_BaseEntity=>m_nMaxCPULevel"] = 2441
  gNetvars["DT_CSGameRulesProxy=>m_spawnStage"] = 3844
  gNetvars["DT_SmokeStack=>m_AmbientLight.m_vPos"] = 2868
  gNetvars["DT_BaseAttributableItem=>m_nFallbackStatTrak"] = 12756
  gNetvars["DT_CSGameRulesProxy=>m_vecPlayAreaMins"] = 3328
  gNetvars["DT_Func_Dust=>m_vecMins"] = 808
  gNetvars["DT_DustTrail=>m_EndSize"] = 2808
  gNetvars["DT_FuncSmokeVolume=>m_maxDrawDistance"] = 3044
  gNetvars["DT_RopeKeyframe=>m_RopeFlags"] = 2576
  gNetvars["DT_BasePlayer=>m_iCoachingTeam"] = 12112
  gNetvars["DT_CSGameRulesProxy=>m_szMatchStatTxt"] = 1644
  gNetvars["DT_BaseGrenade=>m_vecVelocity"] = 276
  gNetvars["DT_CSPlayer=>csnonlocaldata"] = 0
  gNetvars["DT_BaseCSGrenadeProjectile=>m_nExplodeEffectTickBegin"] = 10724
  gNetvars["DT_CSGameRulesProxy=>m_flSpawnSelectionTimeEnd"] = 3836
  gNetvars["DT_Func_Dust=>m_DistMax"] = 2548
  gNetvars["DT_CSPlayer=>m_flGuardianTooFarDistFrac"] = 14708
  gNetvars["DT_CSGameRulesProxy=>m_bMapHasRescueZone"] = 114
  gNetvars["DT_CSGameRulesProxy=>m_bTCantBuy"] = 2480
  gNetvars["DT_BasePlayer=>m_skybox3d.fog.enable"] = 12616
  gNetvars["DT_CSGameRulesProxy=>m_nEndMatchMapGroupVoteTypes"] = 3112
  gNetvars["DT_CSGameRulesProxy=>m_bIsDroppingItems"] = 2176
  gNetvars["DT_BasePlayer=>m_flLastDuckTime"] = 12360
  gNetvars["DT_MaterialModifyControl=>m_iFrameEnd"] = 3300
  gNetvars["DT_CSGameRulesProxy=>m_flCMMItemDropRevealStartTime"] = 2168
  gNetvars["DT_PlantedC4=>m_bBombTicking"] = 10624
  gNetvars["DT_TEShatterSurface=>m_vecForcePos"] = 52
  gNetvars["DT_CSPlayer=>m_bStrafing"] = 14996
  gNetvars["DT_TEFoundryHelpers=>m_iEntity"] = 16
  gNetvars["DT_CSPlayer=>m_iPrimaryAddon"] = 41848
  gNetvars["DT_EnvScreenOverlay=>m_flStartTime"] = 5112
  gNetvars["DT_Func_Dust=>m_LifetimeMax"] = 2544
  gNetvars["DT_BaseBeam=>m_nStartFrame"] = 24
  gNetvars["DT_TeamplayRoundBasedRulesProxy=>m_bInWaitingForPlayers"] = 56
  gNetvars["DT_ParticleSystem=>m_szSnapshotFileName"] = 2536
  gNetvars["DT_PropVehicleDriveable=>m_bEnterAnimOn"] = 10688
  gNetvars["DT_BaseToggle=>m_flMoveTargetTime"] = 2556
  gNetvars["DT_MovieDisplay=>m_bLooping"] = 2521
  gNetvars["DT_BaseAttributableItem=>m_flFallbackWear"] = 12752
  gNetvars["DT_PlayerPing=>m_hPingedEntity"] = 2536
  gNetvars["DT_EnvGasCanister=>m_hSkyboxCopy"] = 10664
  gNetvars["DT_CSGameRulesProxy=>m_nQueuedMatchmakingMode"] = 120
  gNetvars["DT_CSGameRulesProxy=>m_flDMBonusTimeLength"] = 1112
  gNetvars["DT_TEBeamEntPoint=>m_vecEndPoint"] = 96
  gNetvars["DT_RopeKeyframe=>m_Subdiv"] = 3256
  gNetvars["DT_BaseCombatWeapon=>m_iSecondaryAmmoType"] = 12896
  gNetvars["DT_PointCamera=>m_bUseScreenAspectRatio"] = 2549
  gNetvars["DT_BasePlayer=>m_bCameraManScoreBoard"] = 13183
  gNetvars["DT_Team=>m_szTeamFlagImage"] = 2604
  gNetvars["DT_MapVetoPickController=>m_nPhaseStartTick"] = 4880
  gNetvars["DT_PhysPropLootCrate=>m_iHealth"] = 256
  gNetvars["DT_ParticlePerformanceMonitor=>m_bDisplayPerf"] = 2520
  gNetvars["DT_TEMuzzleFlash=>m_nType"] = 44
  gNetvars["DT_TEShatterSurface=>m_vecOrigin"] = 16
  gNetvars["DT_Inferno=>m_nFireEffectTickBegin"] = 5044
  gNetvars["DT_CSPlayer=>m_iWeaponPurchasesThisRound"] = 46360
  gNetvars["DT_CSPlayer=>m_vecOrigin[2]"] = 320
  gNetvars["DT_PropVehicleChoreoGeneric=>m_vehicleView.flFOV"] = 10916
  gNetvars["DT_Beam=>m_nHaloIndex"] = 2544
  gNetvars["DT_TEFireBullets=>m_iSeed"] = 60
  gNetvars["DT_PointCommentaryNode=>m_iszCommentaryFile"] = 10632
  gNetvars["DT_TEWorldDecal=>m_nIndex"] = 28
  gNetvars["DT_ColorCorrection=>m_minFalloff"] = 2532
  gNetvars["DT_EnvProjectedTexture=>m_LightColor"] = 2548
  gNetvars["DT_CSGameRulesProxy=>m_nTournamentPredictionsPct"] = 2164
  gNetvars["DT_CSPlayerResource=>m_iGunGameLevel"] = 18884
  gNetvars["DT_GrassBurn=>m_flGrassBurnClearTime"] = 2520
  gNetvars["DT_CSPlayer=>m_bCanControlObservedBot"] = 47610
  gNetvars["DT_PointCamera=>m_Resolution"] = 2524
  gNetvars["DT_TEBeamEntPoint=>m_nStartEntity"] = 76
  gNetvars["DT_Drone=>m_vecTagPositions[0]"] = 10732
  gNetvars["DT_CSPlayer=>m_bResumeZoom"] = 14634
  gNetvars["DT_TEPhysicsProp=>m_nEffects"] = 64
  gNetvars["DT_ItemDogtags=>m_OwningPlayer"] = 13376
  gNetvars["DT_BaseEntity=>m_iTextureFrameIndex"] = 2444
  gNetvars["DT_BasePlayer=>m_hTonemapController"] = 12748
  gNetvars["DT_CSPlayer=>m_nQuestProgressReason"] = 45868
  gNetvars["DT_BasePlayer=>m_vecVelocity[1]"] = 280
  gNetvars["DT_SmokeStack=>m_flRollSpeed"] = 3008
  gNetvars["DT_CSGameRulesProxy=>m_flSpawnSelectionTimeLoadout"] = 3840
  gNetvars["DT_CSPlayer=>m_isCurrentGunGameTeamLeader"] = 14730
  gNetvars["DT_TEBeamLaser=>m_nEndEntity"] = 80
  gNetvars["DT_BaseTeamObjectiveResource=>m_bPlayingMiniRounds"] = 2536
  gNetvars["DT_BreakableSurface=>m_bIsBroken"] = 2564
  gNetvars["DT_TESparks=>m_nTrailLength"] = 32
  gNetvars["DT_PropVehicleChoreoGeneric=>m_vehicleView.flRollCurveLinear"] = 10912
  gNetvars["DT_EnvGasCanister=>m_bInSkybox"] = 10796
  gNetvars["DT_WeaponCSBase=>m_bBurstMode"] = 13128
  gNetvars["DT_TEBubbles=>m_fSpeed"] = 52
  gNetvars["DT_DangerZone=>m_flExtraRadiusStartTime"] = 2540
  gNetvars["DT_BaseAnimating=>m_nHighlightColorB"] = 2624
  gNetvars["DT_ColorCorrectionVolume=>m_lookupFilename"] = 2608
  gNetvars["DT_SmokeStack=>m_EndSize"] = 2848
  gNetvars["DT_PlantedC4=>m_flTimerLength"] = 10644
  gNetvars["DT_CSPlayer=>m_EquippedLoadoutItemDefIndices"] = 45652
  gNetvars["DT_CSGameRulesProxy=>m_szTournamentEventName"] = 1124
  gNetvars["DT_SpriteTrail=>m_flStartWidthVariance"] = 4224
  gNetvars["DT_ParticleSystem=>m_flStartTime"] = 2532
  gNetvars["DT_BaseBeam=>m_fAmplitude"] = 48
  gNetvars["DT_CSGameRulesProxy=>m_iRoundWinStatus"] = 2472
  gNetvars["DT_WeaponTablet=>m_flShowMapTime"] = 13476
  gNetvars["DT_EnvGasCanister=>m_vecSkyboxOrigin"] = 10780
  gNetvars["DT_TEBeamLaser=>m_nStartEntity"] = 76
  gNetvars["DT_BasePlayer=>m_audio.localSound[4]"] = 12680
  gNetvars["DT_EntityDissolve=>m_flStartTime"] = 2524
  gNetvars["DT_FEPlayerDecal=>m_flCreationTime"] = 2600
  gNetvars["DT_VoteController=>m_iOnlyTeamToVote"] = 2536
  gNetvars["DT_CSPlayer=>m_iProgressBarDuration"] = 41856
  gNetvars["DT_PlayerResource=>m_bAlive"] = 4416
  gNetvars["DT_TESmoke=>m_fScale"] = 32
  gNetvars["DT_VoteController=>m_nVoteOptionCount"] = 2540
  gNetvars["DT_FogController=>m_fog.HDRColorScale"] = 2596
  gNetvars["DT_BasePlayer=>m_viewPunchAngle"] = 12320
  gNetvars["DT_TEPlayerDecal=>m_nEntity"] = 56
  gNetvars["DT_CHostage=>m_isRescued"] = 12080
  gNetvars["DT_DangerZone=>m_flExtraRadiusTotalLerpTime"] = 2544
  gNetvars["DT_WorldVguiText=>m_iTextPanelWidth"] = 3360
  gNetvars["DT_ColorCorrection=>m_bExclusive"] = 2819
  gNetvars["DT_SceneEntity=>m_bIsPlayingBack"] = 2524
  gNetvars["DT_BaseEntity=>m_bSpottedByMask"] = 2432
  gNetvars["DT_BasePlayer=>m_iAmmo"] = 11640
  gNetvars["DT_BaseViewModel=>m_hWeapon"] = 10696
  gNetvars["DT_EconEntity=>m_iReapplyProvisionParity"] = 11672
  gNetvars["DT_CSGameRulesProxy=>m_numGlobalGiftsPeriodSeconds"] = 2208
  gNetvars["DT_PointCommentaryNode=>m_iszCommentaryFileNoHDR"] = 10892
  gNetvars["DT_BaseCSGrenade=>m_fThrowTime"] = 13268
  gNetvars["DT_ParticleSmokeGrenade=>m_MaxColor"] = 2800
  gNetvars["DT_DynamicLight=>m_Radius"] = 2524
  gNetvars["DT_BaseAttributableItem=>m_nFallbackPaintKit"] = 12744
  gNetvars["DT_TEShatterSurface=>m_uchBackColor[0]"] = 87
  gNetvars["DT_FireTrail=>m_nAttachment"] = 2756
  gNetvars["DT_EnvGasCanister=>m_vecParabolaDirection"] = 10764
  gNetvars["DT_BasePlayer=>m_iFOVStart"] = 12776
  gNetvars["DT_Sun=>HDRColorScale"] = 0
  gNetvars["DT_WeaponTablet=>m_nContractKillGridIndex"] = 13456
  gNetvars["DT_CSGameRulesProxy=>m_SurvivalGameRuleDecisionTypes"] = 4904
  gNetvars["DT_Beam=>m_fEndWidth"] = 2640
  gNetvars["DT_CSPlayerResource=>m_bEndMatchNextMapAllVoted"] = 27532
  gNetvars["DT_BaseTeamObjectiveResource=>m_bTeamCanCap"] = 4508
  gNetvars["DT_InfoOverlayAccessor=>m_iTextureFrameIndex"] = 2444
  gNetvars["DT_FogController=>m_fog.colorSecondary"] = 2540
  gNetvars["DT_TEDynamicLight=>m_vecOrigin"] = 16
  gNetvars["DT_FuncSmokeVolume=>m_ParticleSpacingDistance"] = 3024
  gNetvars["DT_ParticleSmokeGrenade=>m_FadeStartTime"] = 2776
  gNetvars["DT_EnvWind=>m_iMinGust"] = 2544
  gNetvars["DT_BaseEntity=>m_flMaxFallVelocity"] = 220
  gNetvars["DT_TEPlayerDecal=>m_vecStart"] = 32
  gNetvars["DT_Tesla=>m_iszSpriteName"] = 2624
  gNetvars["DT_StatueProp=>m_bShatter"] = 10692
  gNetvars["DT_FogController=>m_fog.dirPrimary"] = 2524
  gNetvars["DT_MovieDisplay=>m_szMovieFilename"] = 2522
  gNetvars["DT_Precipitation=>m_nPrecipType"] = 2560
  gNetvars["DT_TEBeamRingPoint=>m_flEndRadius"] = 92
  gNetvars["DT_CSPlayer=>m_bInNoDefuseArea"] = 14698
  gNetvars["DT_CSPlayer=>m_hPlayerPing"] = 41968
  gNetvars["DT_ColorCorrection=>m_bClientSide"] = 2818
  gNetvars["DT_WorldVguiText=>m_bEnabled"] = 2520
  gNetvars["DT_BasePlayer=>m_iObserverMode"] = 13176
  gNetvars["DT_CSPlayer=>m_bIsLookingAtWeapon"] = 47392
  gNetvars["DT_FireTrail=>m_flLifetime"] = 2760
  gNetvars["DT_CSPlayer=>m_flFlashDuration"] = 42016
  gNetvars["DT_CSGameRulesProxy=>m_iNumGunGameProgressiveWeaponsCT"] = 128
  gNetvars["DT_EnvProjectedTexture=>m_flFarZ"] = 2580
  gNetvars["DT_BasePlayer=>m_iDefaultFOV"] = 13100
  gNetvars["DT_CSGameRulesProxy=>m_RetakeRules"] = 5056
  gNetvars["DT_EnvTonemapController=>m_flTonemapMinAvgLum"] = 2556
  gNetvars["DT_World=>m_flMaxOccludeeArea"] = 2552
  gNetvars["DT_TEExplosion=>m_nFrameRate"] = 36
  gNetvars["DT_SurvivalSpawnChopper=>m_vecOrigin[2]"] = 320
  gNetvars["DT_TESpriteSpray=>m_nModelIndex"] = 40
  gNetvars["DT_SteamJet=>m_nType"] = 2784
  gNetvars["DT_TEFootprintDecal=>m_nIndex"] = 56
  gNetvars["DT_EntityFreezing=>m_flFrozen"] = 2732
  gNetvars["DT_WeaponBaseItem=>m_bRedraw"] = 13276
  gNetvars["DT_WeaponTablet=>m_vecNotificationTimestamps"] = 0
  gNetvars["DT_TEProjectedDecal=>m_flDistance"] = 40
  gNetvars["DT_BaseBeam=>m_nFrameRate"] = 28
  gNetvars["DT_PlayerResource=>m_iHealth"] = 4484
  gNetvars["DT_SporeExplosion=>m_flParticleLifetime"] = 2760
  gNetvars["DT_CSPlayer=>m_bPlayerDominated"] = 46228
  gNetvars["DT_BaseEntity=>m_nModelIndex"] = 600
  gNetvars["DT_TEDust=>m_vecDirection"] = 36
  gNetvars["DT_BeamSpotlight=>m_flSpotlightMaxLength"] = 2536
  gNetvars["DT_CSPlayer=>m_bHasMovedSinceSpawn"] = 14661
  gNetvars["DT_PropCounter=>m_flDisplayValue"] = 10624
  gNetvars["DT_BasePlayer=>deadflag"] = 12756
  gNetvars["DT_CascadeLight=>m_bUseLightEnvAngles"] = 2545
  gNetvars["DT_WeaponNOVA=>m_reloadState"] = 13268
  gNetvars["DT_BaseAnimating=>m_flModelScale"] = 10056
  gNetvars["DT_BaseBeam=>r"] = 52
  gNetvars["DT_MaterialModifyControl=>m_flFloatLerpStartValue"] = 3316
  gNetvars["DT_CSGameRulesProxy=>m_iNumConsecutiveTerroristLoses"] = 3200
  gNetvars["DT_RopeKeyframe=>m_nMaxGPULevel"] = 2443
  gNetvars["DT_BaseAttributableItem=>m_ProviderType"] = 11684
  gNetvars["DT_BeamSpotlight=>m_flSpotlightGoalWidth"] = 2540
  gNetvars["DT_CFish=>m_z"] = 10704
  gNetvars["DT_BasePlayer=>m_Local"] = 12220
  gNetvars["DT_CSGameRulesProxy=>m_iMatchStats_PlayersAlive_CT"] = 2608
  gNetvars["DT_BaseWeaponWorldModel=>m_hCombatWeaponParent"] = 10736
  gNetvars["DT_TEBloodSprite=>a"] = 52
  gNetvars["DT_EntityDissolve=>m_flFadeOutModelStart"] = 2536
  gNetvars["DT_BasePlayer=>m_iBonusChallenge"] = 12868
  gNetvars["DT_EconEntity=>m_nFallbackPaintKit"] = 12744
  gNetvars["DT_PlayerResource=>m_iCoachingTeam"] = 4744
  gNetvars["DT_PhysPropLootCrate=>m_bRenderInPSPM"] = 10740
  gNetvars["DT_PropVehicleChoreoGeneric=>m_vehicleView.flYawMax"] = 10924
  gNetvars["DT_Embers=>m_nDensity"] = 2520
  gNetvars["DT_FogController=>m_fog.ZoomFogScale"] = 2592
  gNetvars["DT_BasePlayer=>m_flMaxspeed"] = 12872
  gNetvars["DT_BaseViewModel=>m_nResetEventsParity"] = 2632
  gNetvars["DT_BreakableSurface=>m_nSurfaceType"] = 2568
  gNetvars["DT_Sprite=>m_flBrightnessTime"] = 2560
  gNetvars["DT_EnvScreenEffect=>m_flDuration"] = 2520
  gNetvars["DT_CSPlayer=>m_iMatchStats_Objective"] = 43164
  gNetvars["DT_CHostage=>m_leader"] = 12064
  gNetvars["DT_BaseViewModel=>m_fEffects"] = 240
  gNetvars["DT_CSPlayer=>m_flGroundAccelLinearFracLastTime"] = 41888
  gNetvars["DT_BasePlayer=>m_nJumpTimeMsecs"] = 12304
  gNetvars["DT_DangerZoneController=>m_hTheFinalZone"] = 2744
  gNetvars["DT_BaseTeamObjectiveResource=>m_iTeamIcons"] = 2716
  gNetvars["DT_TEBloodStream=>r"] = 40
  gNetvars["DT_TEEffectDispatch=>m_nColor"] = 112
  gNetvars["DT_FuncMoveLinear=>m_fFlags"] = 260
  gNetvars["DT_PlantedC4=>m_bBombDefused"] = 10672
  gNetvars["DT_AI_BaseNPC=>m_lifeState"] = 607
  gNetvars["DT_TEBloodSprite=>r"] = 40
  gNetvars["DT_EnvGasCanister=>m_bLaunchedFromWithinWorld"] = 10760
  gNetvars["DT_CSGameRulesProxy=>m_arrFeaturedGiftersGifts"] = 2228
  gNetvars["DT_EnvScreenEffect=>m_nType"] = 2524
  gNetvars["DT_CSPlayer=>m_bInBuyZone"] = 14697
  gNetvars["DT_CSPlayerResource=>m_iMatchStats_CashEarned_Total"] = 26424
  gNetvars["DT_TEBubbleTrail=>m_nCount"] = 48
  gNetvars["DT_CSPlayerResource=>m_iMatchStats_LiveTime_Total"] = 25644
  gNetvars["DT_CSPlayerResource=>m_nMusicID"] = 19664
  gNetvars["DT_SceneEntity=>m_flForceClientTime"] = 2532
  gNetvars["DT_CSPlayer=>m_angEyeAngles"] = 45948
  gNetvars["DT_FuncAreaPortalWindow=>m_flFadeStartDist"] = 2520
  gNetvars["DT_CSPlayer=>m_iBlockingUseActionInProgress"] = 14644
  gNetvars["DT_SpriteTrail=>m_flLifeTime"] = 4212
  gNetvars["DT_CSPlayer=>m_bHasDefuser"] = 45960
  gNetvars["DT_AI_BaseNPC=>m_bImportanRagdoll"] = 12072
  gNetvars["DT_BasePlayer=>m_hViewEntity"] = 13116
  gNetvars["DT_TESmoke=>m_nFrameRate"] = 36
  gNetvars["DT_CSPlayerResource=>m_iLifetimeEnd"] = 7896
  gNetvars["DT_Func_Dust=>m_Color"] = 2520
  gNetvars["DT_BasePlayer=>m_flFOVTime"] = 12808
  gNetvars["DT_BaseEntity=>m_hEffectEntity"] = 2456
  gNetvars["DT_ParticleSystem=>m_bActive"] = 2528
  gNetvars["DT_LightGlow=>m_flGlowProxySize"] = 2756
  gNetvars["DT_BasePlayer=>m_vecConstraintCenter"] = 13128
  gNetvars["DT_CSPlayer=>m_bIsGrabbingHostage"] = 14641
  gNetvars["DT_BasePlayer=>m_afPhysicsFlags"] = 13036
  gNetvars["DT_EntityDissolve=>m_flFadeInLength"] = 2548
  gNetvars["DT_TEBSPDecal=>m_vecOrigin"] = 16
  gNetvars["DT_FuncSmokeVolume=>m_MaterialName"] = 2764
  gNetvars["DT_BasePlayer=>m_vecVelocity[0]"] = 276
  gNetvars["DT_FEPlayerDecal=>m_unAccountID"] = 2524
  gNetvars["DT_BaseGrenade=>m_fFlags"] = 260
  gNetvars["DT_TEBloodSprite=>m_vecOrigin"] = 16
  gNetvars["DT_CSGameRulesProxy=>m_nTerroristTimeOuts"] = 56
  gNetvars["DT_DangerZoneController=>m_vecEndGameCircleStart"] = 2524
  gNetvars["DT_SunlightShadowControl=>m_bEnableShadows"] = 2840
  gNetvars["DT_TEPhysicsProp=>m_nFlags"] = 60
  gNetvars["DT_EconEntity=>m_iItemIDLow"] = 580
  gNetvars["DT_BaseCSGrenade=>m_bRedraw"] = 13264
  gNetvars["DT_CSPlayerResource=>m_iPlayerC4"] = 5724
  gNetvars["DT_FogController=>m_fog.maxdensityLerpTo"] = 2576
  gNetvars["DT_BasePlayer=>m_hLastWeapon"] = 13044
  gNetvars["DT_Func_Dust=>m_DustFlags"] = 2560
  gNetvars["DT_CSPlayer=>m_fImmuneToGunGameDamageTime"] = 14652
  gNetvars["DT_CChicken=>m_jumpedThisFrame"] = 10728
  gNetvars["DT_WeaponCSBase=>m_fAccuracyPenalty"] = 13104
  gNetvars["DT_WeaponTablet=>m_flUpgradeExpirationTime"] = 0
  gNetvars["DT_WeaponTablet=>m_nContractKillGridHighResIndex"] = 13460
  gNetvars["DT_PointCamera=>m_flFogStart"] = 2536
  gNetvars["DT_MovieDisplay=>m_szGroupName"] = 2650
  gNetvars["DT_Func_Dust=>m_bAffectedByWind"] = 2556
  gNetvars["DT_BasePlayer=>m_hPostProcessCtrl"] = 14248
  gNetvars["DT_BaseAnimating=>m_nHitboxSet"] = 2556
  gNetvars["DT_BaseAnimating=>m_ScaleType"] = 10060
  gNetvars["DT_RopeKeyframe=>moveparent"] = 328
  gNetvars["DT_AI_BaseNPC=>m_iSpeedModSpeed"] = 12064
  gNetvars["DT_BeamSpotlight=>m_nRotationAxis"] = 2524
  gNetvars["DT_CSGameRulesProxy=>m_iMatchStats_RoundResults"] = 2488
  gNetvars["DT_FuncConveyor=>m_flConveyorSpeed"] = 2520
  gNetvars["DT_VoteController=>m_nPotentialVotes"] = 2564
  gNetvars["DT_CSGameRulesProxy=>m_flSpawnSelectionTimeStart"] = 3832
  gNetvars["DT_CSGameRulesProxy=>m_flCTTimeOutRemaining"] = 52
  gNetvars["DT_Drone=>m_hDeliveryCargo"] = 10716
  gNetvars["DT_TEPhysicsProp=>m_nSkin"] = 56
  gNetvars["DT_BasePlayer=>m_skybox3d.fog.end"] = 12584
  gNetvars["DT_CSPlayer=>m_bHasParachute"] = 45904
  gNetvars["DT_MapVetoPickController=>m_nMapId0"] = 3084
  gNetvars["DT_MapVetoPickController=>m_nCurrentPhase"] = 4876
  gNetvars["DT_FuncSmokeVolume=>m_triggerBloat"] = 835
  gNetvars["DT_BasePlayer=>m_flConstraintSpeedFactor"] = 13148
  gNetvars["DT_SporeTrail=>m_flEndSize"] = 2776
  gNetvars["DT_BasePlayer=>m_fFlags"] = 260
  gNetvars["DT_BaseAnimatingOverlay=>overlay_vars"] = 0
  gNetvars["DT_PlantedC4=>m_flDefuseCountDown"] = 10668
  gNetvars["DT_PointCommentaryNode=>m_bActive"] = 10624
  gNetvars["DT_BaseFlex=>m_blinktoggle"] = 11220
  gNetvars["DT_BaseTeamObjectiveResource=>m_iPreviousPoints"] = 3740
  gNetvars["DT_TEEffectDispatch=>m_bPositionsAreRelativeToEntity"] = 113
  gNetvars["DT_TEImpact=>m_vecOrigin"] = 16
  gNetvars["DT_CSPlayerResource=>m_iMatchStats_UtilityDamage_Total"] = 26684
  gNetvars["DT_CSPlayer=>m_bInBombZone"] = 14696
  gNetvars["DT_BasePlayer=>m_aimPunchAngle"] = 12332
  gNetvars["DT_BasePlayer=>localdata"] = 0
  gNetvars["DT_BaseGrenade=>m_bIsLive"] = 10625
  gNetvars["DT_PhysicsPropMultiplayer=>m_collisionMaxs"] = 10712
  gNetvars["DT_TEShatterSurface=>m_uchBackColor[1]"] = 88
  gNetvars["DT_CSGameRulesProxy=>m_TeamRespawnWaveTimes"] = 2848
  gNetvars["DT_Ragdoll=>m_ragAngles[0]"] = 10912
  gNetvars["DT_Team=>m_iTeamNum"] = 2920
  gNetvars["DT_DustTrail=>m_Opacity"] = 2772
  gNetvars["DT_CascadeLight=>m_LightColorScale"] = 2552
  gNetvars["DT_DynamicLight=>m_LightStyle"] = 2521
  gNetvars["DT_MaterialModifyControl=>m_szMaterialName"] = 2520
  gNetvars["DT_BaseCSGrenadeProjectile=>m_vInitialVelocity"] = 10704
  gNetvars["DT_BaseCombatCharacter=>m_flTimeOfLastInjury"] = 12028
  gNetvars["DT_BaseAnimating=>m_nNewSequenceParity"] = 2628
  gNetvars["DT_MapVetoPickController=>m_nStartingSide0"] = 4620
  gNetvars["DT_TEExplosion=>m_chMaterialType"] = 56
  gNetvars["DT_SporeExplosion=>m_flSpawnRadius"] = 2772
  gNetvars["DT_Ragdoll_Attached=>m_attachmentPointRagdollSpace"] = 11432
  gNetvars["DT_BaseFlex=>m_flexWeight"] = 10792
  gNetvars["DT_TESprite=>m_nBrightness"] = 36
  gNetvars["DT_DangerZoneController=>m_bMissionControlledExplosions"] = 2521
  gNetvars["DT_PoseController=>m_hProps"] = 2520
  gNetvars["DT_SporeExplosion=>m_flSpawnRate"] = 2756
  gNetvars["DT_PhysBoxMultiplayer=>m_fMass"] = 2536
  gNetvars["DT_EntityParticleTrail=>m_hConstraintEntity"] = 2776
  gNetvars["DT_CSGameRulesProxy=>m_eRoundWinReason"] = 2476
  gNetvars["DT_CSPlayer=>csteamdata"] = 0
  gNetvars["DT_TEEnergySplash=>m_bExplosive"] = 40
  gNetvars["DT_TEFireBullets=>m_fInaccuracy"] = 64
  gNetvars["DT_SteamJet=>m_JetLength"] = 2776
  gNetvars["DT_BasePlayer=>m_PlayerFog.m_hCtrl"] = 14260
  gNetvars["DT_PlayerResource=>m_bConnected"] = 2788
  gNetvars["DT_CSPlayerResource=>m_isHostageFollowingSomeone"] = 5768
  gNetvars["DT_BreachChargeProjectile=>m_bShouldExplode"] = 10704
  gNetvars["DT_MapVetoPickController=>m_nPhaseDurationTicks"] = 4884
  gNetvars["DT_ProxyToggle=>blah"] = 0
  gNetvars["DT_FuncRotating=>m_angRotation[0]"] = 300
  gNetvars["DT_EnvProjectedTexture=>m_flBrightnessScale"] = 2544
  gNetvars["DT_CSPlayer=>m_bMadeFinalGunGameProgressiveKill"] = 14662
  gNetvars["DT_WaterLODControl=>m_flCheapWaterEndDistance"] = 2524
  gNetvars["DT_PropVehicleDriveable=>m_nBoostTimeLeft"] = 10644
  gNetvars["DT_RocketTrail=>m_nAttachment"] = 2832
  gNetvars["DT_CSPlayerResource=>m_szClan"] = 17324
  gNetvars["DT_TEExplosion=>m_nRadius"] = 60
  gNetvars["DT_EntityDissolve=>m_vDissolverOrigin"] = 2560
  gNetvars["DT_VoteController=>m_bIsYesNoVote"] = 2570
  gNetvars["DT_BasePlayer=>m_nDuckTimeMsecs"] = 12296
  gNetvars["DT_SmokeStack=>m_Rate"] = 2852
  gNetvars["DT_CSPlayer=>m_iMatchStats_Assists"] = 42924
  gNetvars["DT_BaseEntity=>m_cellZ"] = 132
  gNetvars["DT_BaseEntity=>m_nMaxGPULevel"] = 2443
  gNetvars["DT_TEBeamSpline=>m_vecPoints"] = 0
  gNetvars["DT_CSPlayer=>m_iMatchStats_LiveTime"] = 42684
  gNetvars["DT_BreakableSurface=>m_nNumWide"] = 2524
  gNetvars["DT_BaseTeamObjectiveResource=>m_iWarnOnCap"] = 4836
  gNetvars["DT_CSPlayerResource=>m_hostageRescueX"] = 5828
  gNetvars["DT_PropVehicleChoreoGeneric=>m_vehicleView.flRollCurveZero"] = 10908
  gNetvars["DT_BaseWeaponWorldModel=>m_nBody"] = 2592
  gNetvars["DT_AI_BaseNPC=>m_bFadeCorpse"] = 12070
  gNetvars["DT_BaseCSGrenadeProjectile=>m_nBounces"] = 10716
  gNetvars["DT_CSPlayer=>m_iNumRoundKillsHeadshots"] = 14680
  gNetvars["DT_LightGlow=>m_nMaxDist"] = 2532
  gNetvars["DT_SpriteTrail=>m_flStartWidth"] = 4216
  gNetvars["DT_EntityParticleTrail=>m_flStartSize"] = 2768
  gNetvars["DT_BaseEntity=>m_flSimulationTime"] = 616
  gNetvars["DT_CSRagdoll=>m_vecOrigin"] = 312
  gNetvars["DT_BasePlayer=>m_bAllowAutoMovement"] = 12368
  gNetvars["DT_Team=>m_szTeamname"] = 2540
  gNetvars["DT_BaseCSGrenade=>m_bLoopingSoundPlaying"] = 13272
  gNetvars["DT_EnvTonemapController=>m_flCustomBloomScaleMinimum"] = 2536
  gNetvars["DT_TEPlayerAnimEvent=>m_nData"] = 24
  gNetvars["DT_BaseCombatWeapon=>m_hWeaponWorldModel"] = 12884
  gNetvars["DT_CSPlayer=>m_bNightVisionOn"] = 41881
  gNetvars["DT_MapVetoPickController=>m_nTeamWinningCoinToss"] = 2540
  gNetvars["DT_CSPlayerResource=>m_iControlledByPlayer"] = 8484
  gNetvars["DT_BaseTeamObjectiveResource=>m_iTeamOverlays"] = 2972
  gNetvars["DT_FogController=>m_fog.endLerpTo"] = 2572
  gNetvars["DT_TEFireBullets=>m_nItemDefIndex"] = 20
  gNetvars["DT_BasePlayer=>m_hConstraintEntity"] = 13124
  gNetvars["DT_CSGameRulesProxy=>m_flTabletHexOriginY"] = 3852
  gNetvars["DT_CSPlayer=>m_iMatchStats_EquipmentValue"] = 42324
  gNetvars["DT_CHostage=>m_vel"] = 12068
  gNetvars["DT_Tesla=>m_SoundName"] = 2560
  gNetvars["DT_FEPlayerDecal=>m_vecRight"] = 2560
  gNetvars["DT_FuncSmokeVolume=>m_DensityRampSpeed"] = 3028
  gNetvars["DT_EnvScreenOverlay=>m_flOverlayTimes"] = 0
  gNetvars["DT_TEShatterSurface=>m_flShardSize"] = 72
  gNetvars["DT_FogController=>m_fog.colorSecondaryLerpTo"] = 2548
  gNetvars["DT_BaseCSGrenadeProjectile=>m_vecExplodeEffectOrigin"] = 10728
  gNetvars["DT_CSPlayerResource=>m_nCharacterDefIndex"] = 18364
  gNetvars["DT_TEBSPDecal=>m_nIndex"] = 32
  gNetvars["DT_TEFootprintDecal=>m_vecOrigin"] = 16
  gNetvars["DT_ShadowControl=>m_bDisableShadows"] = 2540
  gNetvars["DT_ParticleSystem=>m_hOwnerEntity"] = 332
  gNetvars["DT_FireSmoke=>m_nFlags"] = 2532
  gNetvars["DT_TEFizz=>m_nCurrent"] = 28
  gNetvars["DT_TEFizz=>m_nEntity"] = 16
  gNetvars["DT_CSGameRulesProxy=>m_bHasMatchStarted"] = 1104
  gNetvars["DT_MaterialModifyControl=>m_flFloatLerpEndValue"] = 3320
  gNetvars["DT_WeaponCSBase=>m_weaponMode"] = 13080
  gNetvars["DT_EconEntity=>m_Item"] = 11712
  gNetvars["DT_BaseCombatWeapon=>m_iSecondaryReserveAmmoCount"] = 12912
  gNetvars["DT_BreakableSurface=>m_flPanelHeight"] = 2536
  gNetvars["DT_BaseTeamObjectiveResource=>m_iNumControlPoints"] = 2528
  gNetvars["DT_EnvDOFController=>m_flFarBlurDepth"] = 2536
  gNetvars["DT_SpriteTrail=>m_vecSkyboxOrigin"] = 4236
  gNetvars["DT_BaseViewModel=>m_hOwner"] = 10700
  gNetvars["DT_Beam=>m_nNumBeamEnts"] = 2536
  gNetvars["DT_BasePlayer=>m_bDucking"] = 12357
  gNetvars["DT_TEShatterSurface=>m_vecForce"] = 40
  gNetvars["DT_TEBSPDecal=>m_nEntity"] = 28
  gNetvars["DT_WeaponTablet=>m_bTabletReceptionIsBlocked"] = 13464
  gNetvars["DT_EnvProjectedTexture=>m_flProjectionSize"] = 2872
  gNetvars["DT_BaseTeamObjectiveResource=>m_bCPIsVisible"] = 2644
  gNetvars["DT_PointCamera=>m_flFogEnd"] = 2540
  gNetvars["DT_CSPlayerResource=>m_iMVPs"] = 5876
  gNetvars["DT_ParticleSystem=>m_iParentAttachment"] = 748
  gNetvars["DT_TEEnergySplash=>m_vecPos"] = 16
  gNetvars["DT_TEDynamicLight=>r"] = 32
  gNetvars["DT_BumpMineProjectile=>m_bArmed"] = 10724
  gNetvars["DT_TERadioIcon=>m_iAttachToClient"] = 16
  gNetvars["DT_PropVehicleChoreoGeneric=>m_vehicleView.flPitchMax"] = 10932
  gNetvars["DT_RopeKeyframe=>m_hEndPoint"] = 3248
  gNetvars["DT_BasePlayer=>m_iHideHUD"] = 12292
  gNetvars["DT_CSRagdoll=>m_vecRagdollVelocity"] = 10752
  gNetvars["DT_RopeKeyframe=>m_nMinCPULevel"] = 2440
  gNetvars["DT_Beam=>m_flFrameRate"] = 2520
  gNetvars["DT_CSPlayer=>m_bHud_MiniScoreHidden"] = 45994
  gNetvars["DT_TEBeamEnts=>m_nEndEntity"] = 80
  gNetvars["DT_FuncSmokeVolume=>m_usSolidFlags"] = 832
  gNetvars["DT_CSRagdoll=>m_flDeathYaw"] = 10784
  gNetvars["DT_PlayerPing=>m_iType"] = 2540
  gNetvars["DT_BaseEntity=>m_bSpotted"] = 2365
  gNetvars["DT_ItemDogtags=>m_KillingPlayer"] = 13380
  gNetvars["DT_CSPlayerResource=>m_nPersonaDataPublicLevel"] = 19924
  gNetvars["DT_CHostage=>m_flRescueStartTime"] = 12088
  gNetvars["DT_BaseBeam=>m_nSpeed"] = 68
  gNetvars["DT_TEBloodSprite=>m_nSize"] = 64
  gNetvars["DT_CSGameRulesProxy=>m_SurvivalRules"] = 3328
  gNetvars["DT_VGuiScreen=>m_fScreenFlags"] = 2572
  gNetvars["DT_FuncAreaPortalWindow=>m_flFadeDist"] = 2524
  gNetvars["DT_TESpriteSpray=>m_fNoise"] = 48
  gNetvars["DT_BaseTeamObjectiveResource=>m_iszWarnSound"] = 0
  gNetvars["DT_Prop_Hallucination=>m_fVisibleTime"] = 10652
  gNetvars["DT_EnvDOFController=>m_flNearBlurDepth"] = 2524
  gNetvars["DT_World=>m_bStartDark"] = 2548
  gNetvars["DT_BaseViewModel=>m_nBody"] = 2592
  gNetvars["DT_RopeKeyframe=>m_iEndAttachment"] = 3254
  gNetvars["DT_WeaponTablet=>m_flScanProgress"] = 13468
  gNetvars["DT_BumpMineProjectile=>m_vecParentBonePos"] = 10712
  gNetvars["DT_BasePlayer=>m_iBonusProgress"] = 12864
  gNetvars["DT_BaseBeam=>g"] = 56
  gNetvars["DT_PoseController=>m_fInterpolationTime"] = 2548
  gNetvars["DT_SteamJet=>m_Speed"] = 2760
  gNetvars["DT_TEBubbleTrail=>m_flWaterZ"] = 40
  gNetvars["DT_CSPlayerResource=>m_bHasHelmet"] = 6201
  gNetvars["DT_TEPlayerDecal=>m_vecRight"] = 44
  gNetvars["DT_PropVehicleDriveable=>m_vecGunCrosshair"] = 10696
  gNetvars["DT_CSPlayer=>m_cycleLatch"] = 46220
  gNetvars["DT_FuncSmokeVolume=>m_nSurroundType"] = 842
  gNetvars["DT_EnvProjectedTexture=>m_flColorTransitionTime"] = 2568
  gNetvars["DT_BaseEntity=>m_flAnimTime"] = 608
  gNetvars["DT_Embers=>m_bEmit"] = 2532
  gNetvars["DT_CSPlayerResource=>m_nActiveCoinRank"] = 19404
  gNetvars["DT_CSGameRulesProxy=>m_roundData_playerPositions"] = 4384
  gNetvars["DT_BaseTeamObjectiveResource=>m_iUpdateCapHudParity"] = 2540
  gNetvars["DT_SpatialEntity=>m_minFalloff"] = 2532
  gNetvars["DT_SceneEntity=>m_bPaused"] = 2525
  gNetvars["DT_BasePlayer=>m_flDeathTime"] = 13252
  gNetvars["DT_Beam=>m_hAttachEntity"] = 2556
  gNetvars["DT_MaterialModifyControl=>m_szMaterialVarValue"] = 3030
  gNetvars["DT_ParticleSystem=>m_hControlPointEnts"] = 2864
  gNetvars["DT_WeaponCSBase=>m_bReloadVisuallyComplete"] = 13136
  gNetvars["DT_DangerZoneController=>m_flWaveEndTimes"] = 2724
  gNetvars["DT_PhysicsProp=>m_spawnflags"] = 712
  gNetvars["DT_EntityFreezing=>m_vFreezingOrigin"] = 2520
  gNetvars["DT_FEPlayerDecal=>m_unTraceID"] = 2528
  gNetvars["DT_BaseEntity=>movetype"] = 0
  gNetvars["DT_TEPhysicsProp=>m_vecOrigin"] = 16
  gNetvars["DT_Inferno=>m_fireZDelta"] = 3332
  gNetvars["DT_Plasma=>m_nPlasmaModelIndex"] = 2536
  gNetvars["DT_FireSmoke=>m_nFlameFromAboveModelIndex"] = 2540
  gNetvars["DT_EconEntity=>m_hOuter"] = 11676
  gNetvars["DT_Sprite=>m_bWorldSpaceScale"] = 2572
  gNetvars["DT_RocketTrail=>m_Opacity"] = 2784
  gNetvars["DT_Item=>m_bShouldGlow"] = 12848
  gNetvars["DT_CSPlayer=>m_nHeavyAssaultSuitCooldownRemaining"] = 45936
  gNetvars["DT_CSPlayerResource=>m_iMatchStats_5k_Total"] = 24604
  gNetvars["DT_Drone=>m_hMoveToThisEntity"] = 10712
  gNetvars["DT_CSPlayer=>m_iNumGunGameTRKillPoints"] = 14668
  gNetvars["DT_ShadowControl=>m_bEnableLocalLightShadows"] = 2541
  gNetvars["DT_PointCommentaryNode=>m_iszSpeakers"] = 11152
  gNetvars["DT_BaseEntity=>m_clrRender"] = 112
  gNetvars["DT_CSGameRulesProxy=>m_bWarmupPeriod"] = 33
  gNetvars["DT_RocketTrail=>m_StartSize"] = 2804
  gNetvars["DT_SmokeTrail=>m_StartSize"] = 2812
  gNetvars["DT_QuadraticBeam=>m_flWidth"] = 2548
  gNetvars["DT_CSPlayer=>m_flHealthShotBoostExpirationTime"] = 41928
  gNetvars["DT_BasePlayer=>m_vecViewOffset[2]"] = 272
  gNetvars["DT_SmokeStack=>m_vWind"] = 2936
  gNetvars["DT_EnvTonemapController=>m_bUseCustomAutoExposureMin"] = 2520
  gNetvars["DT_Sprite=>m_flFrame"] = 2548
  gNetvars["DT_DustTrail=>m_MinSpeed"] = 2788
  gNetvars["DT_CSPlayerResource=>m_iLifetimeStart"] = 7636
  gNetvars["DT_CSGameRulesProxy=>m_flCMMItemDropRevealEndTime"] = 2172
  gNetvars["DT_Func_Dust=>m_FallSpeed"] = 2552
  gNetvars["DT_RocketTrail=>m_StopEmitTime"] = 2792
  gNetvars["DT_CSGameRulesProxy=>m_bIsQuestEligible"] = 2177
  gNetvars["DT_CSPlayer=>m_rank"] = 45880
  gNetvars["DT_Func_Dust=>m_flSizeMax"] = 2532
  gNetvars["DT_CascadeLight=>m_shadowDirection"] = 2520
  gNetvars["DT_FuncSmokeVolume=>m_MovementSpeed"] = 3036
  gNetvars["DT_BaseEntity=>m_cellX"] = 124
  gNetvars["DT_LightGlow=>m_clrRender"] = 112
  gNetvars["DT_Team=>m_nGGLeaderEntIndex_CT"] = 2896
  gNetvars["DT_Inferno=>m_fireCount"] = 5032
  gNetvars["DT_Func_Dust=>m_nSolidType"] = 834
  gNetvars["DT_BaseEntity=>moveparent"] = 328
  gNetvars["DT_TEMuzzleFlash=>m_vecAngles"] = 28
  gNetvars["DT_Sprite=>m_nAttachment"] = 2540
  gNetvars["DT_ParticleSmokeGrenade=>m_MinColor"] = 2788
  gNetvars["DT_PropVehicleDriveable=>m_hPlayer"] = 10628
  gNetvars["DT_CSGameRulesProxy=>m_flGuardianBuyUntilTime"] = 2484
  gNetvars["DT_CSPlayerResource=>m_hostageRescueY"] = 5844
  gNetvars["DT_BaseCombatCharacter=>bcc_localdata"] = 0
  gNetvars["DT_VGuiScreen=>m_flWidth"] = 2528
  gNetvars["DT_DustTrail=>m_SpawnRate"] = 2756
  gNetvars["DT_CSPlayer=>m_flProgressBarStartTime"] = 41860
  gNetvars["DT_PoseController=>m_fCycleFrequency"] = 2556
  gNetvars["DT_Sun=>m_vDirection"] = 2884
  gNetvars["DT_CascadeLight=>m_envLightShadowDirection"] = 2532
  gNetvars["DT_BaseCSGrenadeProjectile=>m_nExplodeEffectIndex"] = 10720
  gNetvars["DT_CSPlayer=>m_iMoveState"] = 14724
  gNetvars["DT_TEPlantBomb=>m_option"] = 32
  gNetvars["DT_EnvProjectedTexture=>m_bState"] = 2528
  gNetvars["DT_BaseCombatWeapon=>LocalWeaponData"] = 0
  gNetvars["DT_TEImpact=>m_ucFlags"] = 44
  gNetvars["DT_TEBloodSprite=>m_nSprayModel"] = 60
  gNetvars["DT_BaseEntity=>m_usSolidFlags"] = 832
  gNetvars["DT_FootstepControl=>m_destination"] = 2592
  gNetvars["DT_BaseAnimating=>m_nHighlightColorG"] = 2620
  gNetvars["DT_EconEntity=>m_iEntityLevel"] = 560
  gNetvars["DT_PropVehicleDriveable=>m_bHasGun"] = 10764
  gNetvars["DT_FEPlayerDecal=>m_nEntity"] = 2588
  gNetvars["DT_TEEnergySplash=>m_vecDir"] = 28
  gNetvars["DT_CSPlayer=>m_iControlledBotEntIndex"] = 47612
  gNetvars["DT_BaseTeamObjectiveResource=>m_iBaseControlPoints"] = 4700
  gNetvars["DT_SceneEntity=>m_bMultiplayer"] = 2526
  gNetvars["DT_CSGameRulesProxy=>m_iNumConsecutiveCTLoses"] = 3196
  gNetvars["DT_CSPlayer=>m_iClass"] = 45940
  gNetvars["DT_EntityParticleTrail=>m_Info"] = 2756
  gNetvars["DT_CSPlayer=>m_bIsRespawningForDMBonus"] = 14705
  gNetvars["DT_CSPlayerResource=>m_bHasCommunicationAbuseMute"] = 20964
  gNetvars["DT_CSPlayer=>m_iGunGameProgressiveWeaponIndex"] = 14664
  gNetvars["DT_BaseEntity=>m_nMinGPULevel"] = 2442
  gNetvars["DT_TEFireBullets=>m_vecAngles[1]"] = 40
  gNetvars["DT_Sprite=>m_flSpriteFramerate"] = 2544
  gNetvars["DT_CSPlayer=>m_angEyeAngles[0]"] = 45948
  gNetvars["DT_CSRagdoll=>m_hPlayer"] = 10736
  gNetvars["DT_EnvProjectedTexture=>m_nShadowQuality"] = 2856
  gNetvars["DT_TEBeamEntPoint=>m_vecStartPoint"] = 84
  gNetvars["DT_TeamplayRoundBasedRulesProxy=>m_flRestartRoundTime"] = 60
  gNetvars["DT_BaseCombatWeapon=>m_iPrimaryReserveAmmoCount"] = 12908
  gNetvars["DT_LightGlow=>m_angRotation"] = 300
  gNetvars["DT_BreakableSurface=>m_nNumHigh"] = 2528
  gNetvars["DT_TeamplayRoundBasedRulesProxy=>m_bSwitchedTeamsThisRound"] = 46
  gNetvars["DT_CSPlayerResource=>m_iTotalCashSpent"] = 18624
  gNetvars["DT_ShadowControl=>m_shadowDirection"] = 2520
  gNetvars["DT_BaseCombatWeapon=>m_iWeaponOrigin"] = 13000
  gNetvars["DT_TEDecal=>m_vecStart"] = 28
  gNetvars["DT_SmokeStack=>m_JetLength"] = 2856
  gNetvars["DT_BaseViewModel=>m_nModelIndex"] = 600
  gNetvars["DT_EnvScreenOverlay=>m_flOverlayTimes[0]"] = 5072
  gNetvars["DT_PhysicsProp=>m_bAwake"] = 10656
  gNetvars["DT_BasePlayer=>m_chAreaPortalBits"] = 12256
  gNetvars["DT_BaseEntity=>m_flLastMadeNoiseTime"] = 32
  gNetvars["DT_BaseGrenade=>m_hThrower"] = 10656
  gNetvars["DT_FuncOccluder=>m_nOccluderIndex"] = 2520
  gNetvars["DT_CFish=>m_angle"] = 10712
  gNetvars["DT_Func_Dust=>m_SpawnRate"] = 2524
  gNetvars["DT_SteamJet=>m_SpreadSpeed"] = 2756
  gNetvars["DT_TEBreakModel=>m_angRotation[1]"] = 32
  gNetvars["DT_TEDynamicLight=>m_fRadius"] = 28
  gNetvars["DT_SmokeTrail=>m_EndColor"] = 2772
  gNetvars["DT_CSPlayer=>m_bIsWalking"] = 14633
  gNetvars["DT_EnvTonemapController=>m_flCustomBloomScale"] = 2532
  gNetvars["DT_TEEffectDispatch=>m_vStart.z"] = 36
  gNetvars["DT_BreachChargeProjectile=>m_weaponThatThrewMe"] = 10708
  gNetvars["DT_AI_BaseNPC=>m_iDeathFrame"] = 12056
  gNetvars["DT_SmokeTrail=>m_MinDirectedSpeed"] = 2804
  gNetvars["DT_SmokeGrenadeProjectile=>m_bDidSmokeEffect"] = 10772
  gNetvars["DT_Beam=>m_vecEndPos"] = 2672
  gNetvars["DT_TESmoke=>m_nModelIndex"] = 28
  gNetvars["DT_EnvGasCanister=>m_flLaunchTime"] = 10744
  gNetvars["DT_TEBeamRing=>m_nStartEntity"] = 76
  gNetvars["DT_BaseCombatWeapon=>m_hOwner"] = 12848
  gNetvars["DT_CSGameRulesProxy=>m_bGameRestart"] = 84
  gNetvars["DT_CSGameRulesProxy=>m_bBlockersPresent"] = 5312
  gNetvars["DT_DynamicProp=>m_flGlowMaxDist"] = 10692
  gNetvars["DT_CFish=>m_y"] = 10700
  gNetvars["DT_BasePlayer=>m_flNextDecalTime"] = 13256
  gNetvars["DT_TEBubbleTrail=>m_fSpeed"] = 52
  gNetvars["DT_WorldVguiText=>m_clrText"] = 3353
  gNetvars["DT_BaseEntity=>m_cellbits"] = 116
  gNetvars["DT_TeamplayRoundBasedRulesProxy=>m_bInOvertime"] = 44
  gNetvars["DT_TEShatterSurface=>m_uchFrontColor[0]"] = 84
  gNetvars["DT_BaseEntity=>m_flElasticity"] = 768
  gNetvars["DT_TEBloodStream=>g"] = 44
  gNetvars["DT_PlayerPing=>m_bUrgent"] = 2548
  gNetvars["DT_CFish=>m_lifeState"] = 607
  gNetvars["DT_CSPlayer=>m_hCarriedHostageProp"] = 41980
  gNetvars["DT_Func_LOD=>m_nDisappearMaxDist"] = 2524
  gNetvars["DT_BaseEntity=>m_flShadowCastDistance"] = 928
  gNetvars["DT_EnvDOFController=>m_flFarFocusDepth"] = 2532
  gNetvars["DT_CSGameRulesProxy=>m_roundData_playerXuids"] = 3864
  gNetvars["DT_LightGlow=>m_nHorizontalSize"] = 2520
  gNetvars["DT_SmokeTrail=>m_SpawnRate"] = 2756
  gNetvars["DT_CSGameRulesProxy=>m_bBombDropped"] = 2468
  gNetvars["DT_SmokeStack=>m_AmbientLight.m_flIntensity"] = 2892
  gNetvars["DT_CSGameRulesProxy=>m_fWarmupPeriodStart"] = 40
  gNetvars["DT_WeaponC4=>m_fArmedTime"] = 13300
  gNetvars["DT_FogController=>m_fog.end"] = 2556
  gNetvars["DT_SunlightShadowControl=>m_shadowDirection"] = 2520
  gNetvars["DT_TEBreakModel=>m_vecSize"] = 40
  gNetvars["DT_MaterialModifyControl=>m_bFloatLerpWrap"] = 3328
  gNetvars["DT_CSGameRulesProxy=>m_roundData_playerTeams"] = 4644
  gNetvars["DT_CSPlayer=>m_vecOrigin"] = 312
  gNetvars["DT_EconEntity=>m_iEntityQuality"] = 556
  gNetvars["DT_CSGameRulesProxy=>m_bMapHasBuyZone"] = 115
  gNetvars["DT_CSRagdoll=>m_flAbsYaw"] = 10788
  gNetvars["DT_TESprite=>m_nModelIndex"] = 28
  gNetvars["DT_SmokeStack=>m_DirLight.m_flIntensity"] = 2920
  gNetvars["DT_Beam=>m_nBeamType"] = 2548
  gNetvars["DT_ColorCorrectionVolume=>m_bEnabled"] = 2592
  gNetvars["DT_EnvTonemapController=>m_flBloomExponent"] = 2540
  gNetvars["DT_World=>m_iszDetailSpriteMaterial"] = 2576
  gNetvars["DT_SunlightShadowControl=>m_flColorTransitionTime"] = 2820
  gNetvars["DT_BRC4Target=>m_bBrokenOpen"] = 10628
  gNetvars["DT_Dronegun=>m_vecAttentionTarget"] = 10624
  gNetvars["DT_CSPlayer=>m_iNumRoundKills"] = 14676
  gNetvars["DT_DangerZone=>m_flExtraRadius"] = 2536
  gNetvars["DT_TEBloodSprite=>m_nDropModel"] = 56
  gNetvars["DT_SmokeStack=>m_flBaseSpread"] = 2864
  gNetvars["DT_BaseAttributableItem=>m_iReapplyProvisionParity"] = 11672
  gNetvars["DT_PropJeep=>m_bHeadlightIsOn"] = 10956
  gNetvars["DT_BasePlayer=>pl"] = 12752
  gNetvars["DT_BasePlayer=>m_bActiveCameraMan"] = 13180
  gNetvars["DT_AI_BaseNPC=>m_iDeathPose"] = 12052
  gNetvars["DT_CSGameRulesProxy=>m_nEndMatchMapVoteWinner"] = 3192
  gNetvars["DT_CSGameRulesProxy=>m_GGProgressiveWeaponKillUpgradeOrderCT"] = 620
  gNetvars["DT_CSPlayerResource=>m_iArmor"] = 6268
  gNetvars["DT_TESpriteSpray=>m_nSpeed"] = 44
  gNetvars["DT_TEShatterSurface=>m_uchFrontColor[1]"] = 85
  gNetvars["DT_PlayerResource=>m_iDeaths"] = 3636
  gNetvars["DT_SteamJet=>m_spawnflags"] = 2792
  gNetvars["DT_CSGameRulesProxy=>m_gamePhase"] = 96
  gNetvars["DT_FuncAreaPortalWindow=>m_iBackgroundModelIndex"] = 2532
  gNetvars["DT_BaseAnimating=>m_nHighlightColorR"] = 2616
  gNetvars["DT_PostProcessController=>m_bMaster"] = 2564
  gNetvars["DT_World=>m_flMinOccluderArea"] = 2556
  gNetvars["DT_Sprite=>m_nBrightness"] = 2556
  gNetvars["DT_BaseCSGrenade=>m_bIsHeldByPlayer"] = 13265
  gNetvars["DT_ColorCorrection=>m_netLookupFilename"] = 2556
  gNetvars["DT_LightGlow=>m_nMinDist"] = 2528
  gNetvars["DT_Ragdoll_Attached=>m_boneIndexAttached"] = 11448
  gNetvars["DT_Sun=>m_nOverlaySize"] = 2880
  gNetvars["DT_SunlightShadowControl=>m_bEnabled"] = 2532
  gNetvars["DT_DynamicLight=>m_Exponent"] = 2528
  gNetvars["DT_CSPlayerResource=>m_iMatchStats_KillReward_Total"] = 25384
  gNetvars["DT_BasePlayer=>m_nDuckJumpTimeMsecs"] = 12300
  gNetvars["DT_BasePlayer=>m_bPoisoned"] = 12367
  gNetvars["DT_CSGameRulesProxy=>m_iBombSite"] = 5320
  gNetvars["DT_EntityParticleTrail=>m_flLifetime"] = 2764
  gNetvars["DT_BaseAttributableItem=>m_iAccountID"] = 584
  gNetvars["DT_BaseAnimating=>m_nBody"] = 2592
  gNetvars["DT_TEEffectDispatch=>m_nDamageType"] = 100
  gNetvars["DT_EnvGasCanister=>m_flSkyboxScale"] = 10792
  gNetvars["DT_CSPlayer=>m_iWeaponPurchasesThisMatch"] = 43644
  gNetvars["DT_DangerZoneController=>m_DangerZones"] = 2556
  gNetvars["DT_Prop_Hallucination=>m_bEnabled"] = 10649
  gNetvars["DT_PointCamera=>m_bFogEnable"] = 2528
  gNetvars["DT_TeamplayRoundBasedRulesProxy=>m_bAwaitingReadyRestart"] = 57
  gNetvars["DT_TEBubbles=>m_nCount"] = 48
  gNetvars["DT_Team=>player_array_element"] = 0
  gNetvars["DT_FuncSmokeVolume=>m_vecMins"] = 808
  gNetvars["DT_BaseCombatWeapon=>m_flTimeWeaponIdle"] = 12916
  gNetvars["DT_SpriteTrail=>m_flSkyboxScale"] = 4248
  gNetvars["DT_TEGlowSprite=>m_vecOrigin"] = 16
  gNetvars["DT_CSPlayer=>m_iAccount"] = 45924
  gNetvars["DT_CSGameRulesProxy=>m_GGProgressiveWeaponOrderT"] = 380
  gNetvars["DT_Sprite=>m_flGlowProxySize"] = 2576
  gNetvars["DT_CSPlayer=>m_totalHitsOnServer"] = 41896
  gNetvars["DT_BaseViewModel=>m_flPlaybackRate"] = 2584
  gNetvars["DT_WeaponCSBase=>m_bSilencerOn"] = 13137
  gNetvars["DT_CChicken=>m_leader"] = 10732
  gNetvars["DT_TEDynamicLight=>m_fDecay"] = 52
  gNetvars["DT_SmokeStack=>m_SpreadSpeed"] = 2836
  gNetvars["DT_EnvProjectedTexture=>m_bAlwaysUpdate"] = 2529
  gNetvars["DT_PropVehicleDriveable=>m_nScannerDisabledVehicle"] = 10656
  gNetvars["DT_BeamSpotlight=>m_flHDRColorScale"] = 2544
  gNetvars["DT_CSPlayer=>m_hSurvivalAssassinationTarget"] = 41924
  gNetvars["DT_TESpriteSpray=>m_nCount"] = 52
  gNetvars["DT_ParticleSystem=>m_iServerControlPointAssignments"] = 2844
  gNetvars["DT_BasePlayer=>m_hUseEntity"] = 13096
  gNetvars["DT_CSPlayer=>m_iAddonBits"] = 41844
  gNetvars["DT_WeaponXM1014=>m_reloadState"] = 13268
  gNetvars["DT_ParadropChopper=>m_hCallingPlayer"] = 10640
  gNetvars["DT_FuncLadder=>m_vecPlayerMountPositionTop"] = 2552
  gNetvars["DT_EntityDissolve=>m_flFadeOutLength"] = 2532
  gNetvars["DT_BaseViewModel=>m_nMuzzleFlashParity"] = 2660
  gNetvars["DT_SmokeStack=>m_flTwist"] = 2948
  gNetvars["DT_Sun=>m_nMaterial"] = 2900
  gNetvars["DT_Drone=>m_vecTagIncrements[0]"] = 11020
  gNetvars["DT_ParticleSystem=>m_angRotation"] = 300
  gNetvars["DT_BaseButton=>m_usable"] = 2568
  gNetvars["DT_EnvProjectedTexture=>m_bLightOnlyTarget"] = 2538
  gNetvars["DT_Team=>m_numMapVictories"] = 2928
  gNetvars["DT_VGuiScreen=>m_flHeight"] = 2532
  gNetvars["DT_CSGameRulesProxy=>m_nHalloweenMaskListSeed"] = 2464
  gNetvars["DT_BasePlayer=>m_ubEFNoInterpParity"] = 13784
  gNetvars["DT_DustTrail=>m_MaxDirectedSpeed"] = 2800
  gNetvars["DT_TEBloodStream=>m_vecDirection"] = 28
  gNetvars["DT_TEEffectDispatch=>m_flMagnitude"] = 80
  gNetvars["DT_BaseAttributableItem=>m_hOuter"] = 11676
  gNetvars["DT_BaseAttributableItem=>m_Item"] = 11712
  gNetvars["DT_DynamicProp=>m_nGlowStyle"] = 10704
  gNetvars["DT_ColorCorrectionVolume=>m_Weight"] = 2604
  gNetvars["DT_PropVehicleDriveable=>m_vecEyeExitEndpoint"] = 10752
  gNetvars["DT_PropVehicleDriveable=>m_nSpeed"] = 10632
  gNetvars["DT_CSRagdoll=>m_nForceBone"] = 9868
  gNetvars["DT_SunlightShadowControl=>m_TextureName"] = 2533
  gNetvars["DT_TELargeFunnel=>m_nModelIndex"] = 28
  gNetvars["DT_EnvDOFController=>m_flNearBlurRadius"] = 2540
  gNetvars["DT_CSPlayer=>m_bInHostageRescueZone"] = 45961
  gNetvars["DT_BasePlayer=>m_skybox3d.scale"] = 12528
  gNetvars["DT_CSPlayerResource=>m_nPersonaDataPublicCommendsLeader"] = 20184
  gNetvars["DT_TEPhysicsProp=>m_clrRender"] = 68
  gNetvars["DT_BasePlayer=>m_skybox3d.fog.colorSecondary"] = 12568
  gNetvars["DT_FireSmoke=>m_flScale"] = 2524
  gNetvars["DT_CSPlayerResource=>m_nPersonaDataPublicCommendsFriendly"] = 20704
  gNetvars["DT_AI_BaseNPC=>m_bIsMoving"] = 12069
  gNetvars["DT_CSPlayer=>m_vecPlayerPatchEconIndices"] = 47472
  gNetvars["DT_BaseCombatCharacter=>m_flNextAttack"] = 11632
  gNetvars["DT_Sun=>glowDistanceScale"] = 0
  gNetvars["DT_FuncSmokeVolume=>m_Density"] = 3040
  gNetvars["DT_CFish=>m_nModelIndex"] = 600
  gNetvars["DT_BaseEntity=>m_angRotation"] = 300
  gNetvars["DT_BaseToggle=>m_movementType"] = 2552
  gNetvars["DT_FEPlayerDecal=>m_rtGcTime"] = 2532
  gNetvars["DT_TEFireBullets=>m_iPlayer"] = 16
  gNetvars["DT_CSPlayer=>m_bIsHoldingLookAtWeapon"] = 47393
  gNetvars["DT_PhysBoxMultiplayer=>m_iPhysicsMode"] = 2532
  gNetvars["DT_CSGameRulesProxy=>m_vecPlayAreaMaxs"] = 3340
  gNetvars["DT_AI_BaseNPC=>m_flTimePingEffect"] = 12048
  gNetvars["DT_EnvScreenOverlay=>m_bIsActive"] = 5120
  gNetvars["DT_TEProjectedDecal=>m_nIndex"] = 44
  gNetvars["DT_TEParticleSystem=>m_vecOrigin[0]"] = 16
  gNetvars["DT_SporeTrail=>m_bEmit"] = 2796
  gNetvars["DT_EnvGasCanister=>m_vecImpactPosition"] = 10676
  gNetvars["DT_PropVehicleChoreoGeneric=>m_vecEyeExitEndpoint"] = 10752
  gNetvars["DT_Sun=>m_bOn"] = 2896
  gNetvars["DT_BaseCombatCharacter=>m_hMyWearables"] = 12036
  gNetvars["DT_BaseCombatCharacter=>m_hMyWeapons"] = 11768
  gNetvars["DT_EnvWind=>m_flInitialWindSpeed"] = 2632
  gNetvars["DT_TEParticleSystem=>m_vecOrigin[1]"] = 20
  gNetvars["DT_CSRagdoll=>m_bClientSideAnimation"] = 10396
  gNetvars["DT_WorldVguiText=>m_szDisplayTextOption"] = 3033
  gNetvars["DT_CSGameRulesProxy=>m_MatchDevice"] = 1100
  gNetvars["DT_TEImpact=>m_iType"] = 40
  gNetvars["DT_TEFootprintDecal=>m_chMaterialType"] = 60
  gNetvars["DT_TEPhysicsProp=>m_vecVelocity"] = 40
  gNetvars["DT_BasePlayer=>m_audio.entIndex"] = 12736
  gNetvars["DT_BaseEntity=>m_nRenderFX"] = 602
  gNetvars["DT_BaseTeamObjectiveResource=>m_bBlocked"] = 7260
  gNetvars["DT_DangerZoneController=>m_flFinalExpansionTime"] = 2552
  gNetvars["DT_TESmoke=>m_vecOrigin"] = 16
  gNetvars["DT_ColorCorrection=>m_flFadeOutDuration"] = 2544
  gNetvars["DT_BasePlayer=>m_ladderSurfaceProps"] = 12800
  gNetvars["DT_CSPlayerResource=>m_hostageRescueZ"] = 5860
  gNetvars["DT_SunlightShadowControl=>m_LightColor"] = 2800
  gNetvars["DT_CSGameRulesProxy=>m_bIsQueuedMatchmaking"] = 116
  gNetvars["DT_DustTrail=>m_SpawnRadius"] = 2812
  gNetvars["DT_BaseTeamObjectiveResource=>m_flPathDistance"] = 6908
  gNetvars["DT_ParadropChopper=>m_vecOrigin"] = 312
  gNetvars["DT_TeamplayRoundBasedRulesProxy=>m_iWinningTeam"] = 48
  gNetvars["DT_EnvGasCanister=>m_bDoImpactEffects"] = 10797
  gNetvars["DT_Embers=>m_nLifetime"] = 2524
  gNetvars["DT_BaseEntity=>m_bSpottedBy"] = 2366
  gNetvars["DT_CSGameRulesProxy=>m_totalRoundsPlayed"] = 100
  gNetvars["DT_BreakableSurface=>m_vNormal"] = 2540
  gNetvars["DT_World=>m_iTimeOfDay"] = 2572
  gNetvars["DT_CSGameRulesProxy=>m_arrTournamentActiveCasterAccounts"] = 2444
  gNetvars["DT_CSPlayerResource=>m_iMatchStats_3k_Total"] = 24084
  gNetvars["DT_BasePlayer=>m_fOnTarget"] = 13092
  gNetvars["DT_FuncLadder=>m_bFakeLadder"] = 2577
  gNetvars["DT_BasePlayer=>m_vecLadderNormal"] = 12848
  gNetvars["DT_CSPlayer=>m_iStartAccount"] = 41892
  gNetvars["DT_CSPlayer=>m_bWaitForNoAttack"] = 14704
  gNetvars["DT_CSPlayer=>m_bIsScoped"] = 14632
  gNetvars["DT_BaseAnimating=>m_nSkin"] = 2588
  gNetvars["DT_EnvWind=>m_EnvWindShared"] = 2520
  gNetvars["DT_PlantedC4=>m_hBombDefuser"] = 10676
  gNetvars["DT_CSPlayer=>m_unCurrentEquipmentValue"] = 45872
  gNetvars["DT_CSPlayerResource=>m_iPlayerVIP"] = 5728
  gNetvars["DT_Team=>m_szTeamLogoImage"] = 2612
  gNetvars["DT_BasePlayer=>m_audio.localSound[5]"] = 12692
  gNetvars["DT_EconEntity=>m_iAccountID"] = 584
  gNetvars["DT_SporeTrail=>m_vecEndColor"] = 2752
  gNetvars["DT_BaseEntity=>m_flUseLookAtAngle"] = 716
  gNetvars["DT_TEGaussExplosion=>m_vecDirection"] = 32
  gNetvars["DT_SpatialEntity=>m_maxFalloff"] = 2536
  gNetvars["DT_BaseTeamObjectiveResource=>m_iTeamInZone"] = 7228
  gNetvars["DT_Func_Dust=>m_Collision"] = 800
  gNetvars["DT_CSGameRulesProxy=>m_SurvivalGameRuleDecisionValues"] = 4968
  gNetvars["DT_TEExplosion=>m_vecNormal"] = 44
  gNetvars["DT_BaseGrenade=>m_DmgRadius"] = 10628
  gNetvars["DT_TEBreakModel=>m_angRotation[2]"] = 36
  gNetvars["DT_PoseController=>m_bPoseValueParity"] = 2540
  gNetvars["DT_SteamJet=>m_StartSize"] = 2764
  gNetvars["DT_SunlightShadowControl=>m_flNorthOffset"] = 2836
  gNetvars["DT_FogController=>m_fog.lerptime"] = 2580
  gNetvars["DT_BaseAnimating=>m_flFrozen"] = 9976
  gNetvars["DT_TEEffectDispatch=>m_nAttachmentIndex"] = 88
  gNetvars["DT_EntityFlame=>m_bCheapEffect"] = 2540
  gNetvars["DT_BaseEntity=>m_iTeamNum"] = 244
  gNetvars["DT_CSPlayerResource=>m_nPersonaDataPublicCommendsTeacher"] = 20444
  gNetvars["DT_MapVetoPickController=>m_nAccountIDs"] = 2828
  gNetvars["DT_DustTrail=>m_StartSize"] = 2804
  gNetvars["DT_TEShowLine=>m_vecEnd"] = 28
  gNetvars["DT_FEPlayerDecal=>m_ubSignature"] = 2605
  gNetvars["DT_BaseBeam=>m_nFadeLength"] = 44
  gNetvars["DT_InfoOverlayAccessor=>m_iOverlayID"] = 2520
  gNetvars["DT_CSPlayer=>m_iMatchStats_Deaths"] = 42804
  gNetvars["DT_BasePlayer=>m_chAreaBits"] = 12224
  gNetvars["DT_FootstepControl=>m_source"] = 2576
  gNetvars["DT_CSPlayer=>m_iMatchStats_UtilityDamage"] = 43404
  gNetvars["DT_Beam=>m_vecOrigin"] = 312
  gNetvars["DT_DynamicProp=>m_bShouldGlow"] = 10696
  gNetvars["DT_Inferno=>m_fireXDelta"] = 2532
  gNetvars["DT_BasePlayer=>m_szLastPlaceName"] = 13748
  gNetvars["DT_PoseController=>m_nFModType"] = 2560
  gNetvars["DT_Plasma=>m_flScale"] = 2524
  gNetvars["DT_BaseEntity=>m_fadeMaxDist"] = 760
  gNetvars["DT_BaseAnimating=>m_flEncodedController"] = 2644
  gNetvars["DT_PlayerResource=>m_iPing"] = 2856
  gNetvars["DT_EconEntity=>m_iItemDefinitionIndex"] = 554
  gNetvars["DT_EnvGasCanister=>m_flZAcceleration"] = 10752
  gNetvars["DT_FuncSmokeVolume=>m_spawnflags"] = 3048
  gNetvars["DT_TEDynamicLight=>b"] = 40
  gNetvars["DT_SporeExplosion=>m_bEmit"] = 2780
  gNetvars["DT_FEPlayerDecal=>m_nPlayer"] = 2584
  gNetvars["DT_TEGlowSprite=>m_nBrightness"] = 40
  gNetvars["DT_VGuiScreen=>m_nPanelName"] = 2536
  gNetvars["DT_TEBreakModel=>m_nCount"] = 72
  gNetvars["DT_SmokeTrail=>m_ParticleLifetime"] = 2788
  gNetvars["DT_MapVetoPickController=>m_nVoteMapIdsList"] = 2800
  gNetvars["DT_MapVetoPickController=>m_nMapId2"] = 3596
  gNetvars["DT_BasePlayer=>m_vecViewOffset[1]"] = 268
  gNetvars["DT_BaseCombatWeapon=>LocalActiveWeaponData"] = 0
  gNetvars["DT_TEExplosion=>m_nFlags"] = 40
  gNetvars["DT_TESprite=>m_fScale"] = 32
  gNetvars["DT_LightGlow=>m_vecOrigin"] = 312
  gNetvars["DT_TEShatterSurface=>m_uchFrontColor[2]"] = 86
  gNetvars["DT_MaterialModifyControl=>m_bNewAnimCommandsSemaphore"] = 3312
  gNetvars["DT_CSPlayer=>m_bIsSpawnRappelling"] = 41901
  gNetvars["DT_BaseEntity=>m_fEffects"] = 240
  gNetvars["DT_MovieDisplay=>m_flVMin"] = 2792
  gNetvars["DT_PoseController=>m_fFModTimeOffset"] = 2564
  gNetvars["DT_TEBreakModel=>m_vecOrigin"] = 16
  gNetvars["DT_DangerZoneController=>m_flStartTime"] = 2548
  gNetvars["DT_EnvProjectedTexture=>m_bCameraSpace"] = 2540
  gNetvars["DT_EnvWind=>m_iMinWind"] = 2532
  gNetvars["DT_CSPlayer=>m_bHasHelmet"] = 45932
  gNetvars["DT_ParticleSmokeGrenade=>m_FadeEndTime"] = 2780
  gNetvars["DT_FEPlayerDecal=>m_nVersion"] = 2604
  gNetvars["DT_EnvTonemapController=>m_flCustomAutoExposureMax"] = 2528
  gNetvars["DT_CSPlayer=>m_nSurvivalTeam"] = 41920
  gNetvars["DT_WorldVguiText=>m_szFont"] = 3289
  gNetvars["DT_Beam=>m_clrRender"] = 112
  gNetvars["DT_EconEntity=>m_OriginalOwnerXuidLow"] = 12736
  gNetvars["DT_BasePlayer=>m_flConstraintWidth"] = 13144
  gNetvars["DT_TEFootprintDecal=>m_nEntity"] = 52
  gNetvars["DT_BaseCombatWeapon=>m_iState"] = 12888
  gNetvars["DT_EconEntity=>m_nFallbackStatTrak"] = 12756
  gNetvars["DT_TEMuzzleFlash=>m_vecOrigin"] = 16
  gNetvars["DT_CSPlayerResource=>m_iCompTeammateColor"] = 7376
  gNetvars["DT_TEBreakModel=>m_angRotation[0]"] = 28
  gNetvars["DT_SmokeStack=>m_Speed"] = 2840
  gNetvars["DT_CSGameRulesProxy=>m_arrFeaturedGiftersAccounts"] = 2212
  gNetvars["DT_CSPlayer=>m_iMatchStats_Kills"] = 42084
  gNetvars["DT_SporeTrail=>m_flSpawnRate"] = 2764
  gNetvars["DT_QuadraticBeam=>m_scrollRate"] = 2544
  gNetvars["DT_EnvWind=>m_flGustDuration"] = 2560
  gNetvars["DT_CSRagdoll=>m_iTeamNum"] = 244
  gNetvars["DT_CHostage=>m_fFlags"] = 260
  gNetvars["DT_PointCommentaryNode=>m_iNodeNumber"] = 11408
  gNetvars["DT_EntityDissolve=>m_nMagnitude"] = 2572
  gNetvars["DT_BeamSpotlight=>m_flRotationSpeed"] = 2528
  gNetvars["DT_TEFireBullets=>m_vecAngles[0]"] = 36
  gNetvars["DT_CSPlayer=>m_flAutoMoveStartTime"] = 15032
  gNetvars["DT_RopeKeyframe=>m_flScrollSpeed"] = 2572
  gNetvars["DT_SporeTrail=>m_flParticleLifetime"] = 2768
  gNetvars["DT_PlayerResource=>m_iAssists"] = 3376
  gNetvars["DT_Embers=>m_nSpeed"] = 2528
  gNetvars["DT_SlideshowDisplay=>m_fMaxSlideTime"] = 2828
  gNetvars["DT_Team=>m_scoreFirstHalf"] = 2884
  gNetvars["DT_TEBubbles=>m_vecMins"] = 16
  gNetvars["DT_EnvWind=>m_flMaxGustDelay"] = 2556
  gNetvars["DT_TEExplosion=>m_nModelIndex"] = 28
  gNetvars["DT_SteamJet=>m_flRollSpeed"] = 2796
  gNetvars["DT_MovieDisplay=>m_bStretchToFill"] = 2778
  gNetvars["DT_BaseEntity=>m_cellY"] = 128
  gNetvars["DT_WeaponC4=>m_bStartedArming"] = 13296
  gNetvars["DT_TEGaussExplosion=>m_nType"] = 28
  gNetvars["DT_TEBeamSpline=>m_vecPoints[0]"] = 16
  gNetvars["DT_EnvGasCanister=>m_nMyZoneIndex"] = 10800
  gNetvars["DT_BaseAnimating=>m_nResetEventsParity"] = 2632
  gNetvars["DT_PointWorldText=>m_textColor"] = 2832
  gNetvars["DT_CSGameRulesProxy=>m_bDMBonusActive"] = 1118
  gNetvars["DT_PointWorldText=>m_szText"] = 2568
  gNetvars["DT_BasePlayer=>m_audio.localSound[6]"] = 12704
  gNetvars["DT_RopeKeyframe=>m_nMinGPULevel"] = 2442
  gNetvars["DT_BasePlayer=>m_hVehicle"] = 13040
  gNetvars["DT_EnvScreenOverlay=>m_iszOverlayNames[0]"] = 2520
  gNetvars["DT_CSGameRulesProxy=>m_iSpectatorSlotCount"] = 136
  gNetvars["DT_BaseCombatCharacter=>m_LastHitGroup"] = 11636
  gNetvars["DT_Drone=>m_bPilotTakeoverAllowed"] = 10720
  gNetvars["DT_BaseBeam=>m_nModelIndex"] = 16
  gNetvars["DT_Func_Dust=>m_vecSpecifiedSurroundingMaxs"] = 856
  gNetvars["DT_BRC4Target=>m_flRadius"] = 10632
  gNetvars["DT_FogController=>m_fog.colorPrimary"] = 2536
  gNetvars["DT_CSPlayer=>m_iMatchStats_EnemiesFlashed"] = 43524
  gNetvars["DT_BaseEntity=>m_iName"] = 340
  gNetvars["DT_BaseAnimating=>m_bClientSideAnimation"] = 10396
  gNetvars["DT_TEBubbles=>m_nModelIndex"] = 44
  gNetvars["DT_BaseAttributableItem=>m_iItemIDLow"] = 580
  gNetvars["DT_QuadraticBeam=>m_targetPosition"] = 2520
  gNetvars["DT_TEProjectedDecal=>m_vecOrigin"] = 16
  gNetvars["DT_CSPlayer=>m_bHasHeavyArmor"] = 45933
  gNetvars["DT_BaseTeamObjectiveResource=>m_iTeamReqCappers"] = 3228
  gNetvars["DT_TESparks=>m_nMagnitude"] = 28
  gNetvars["DT_BaseEntity=>m_vecMaxs"] = 820
  gNetvars["DT_BaseEntity=>m_Collision"] = 800
  gNetvars["DT_PhysBox=>m_mass"] = 2520
  gNetvars["DT_TEBloodStream=>a"] = 52
  gNetvars["DT_FireSmoke=>m_flStartScale"] = 2520
  gNetvars["DT_MapVetoPickController=>m_nDraftType"] = 2536
  gNetvars["DT_EnvGasCanister=>m_flWorldEnterTime"] = 10776
  gNetvars["DT_BaseViewModel=>m_nViewModelIndex"] = 10688
  gNetvars["DT_WeaponCSBaseGun=>m_zoomLevel"] = 13264
  gNetvars["DT_CSPlayer=>m_nDeathCamMusic"] = 46004
  gNetvars["DT_TEFireBullets=>m_weapon"] = 48
  gNetvars["DT_BaseAnimating=>m_flCycle"] = 2580
  gNetvars["DT_CSPlayerResource=>m_iMatchStats_4k_Total"] = 24344
  gNetvars["DT_Beam=>moveparent"] = 328
  gNetvars["DT_CSGameRulesProxy=>m_SpawnTileState"] = 3608
  gNetvars["DT_CSGameRulesProxy=>m_flNextRespawnWave"] = 2976
  gNetvars["DT_EnvGasCanister=>m_flInitialZSpeed"] = 10748
  gNetvars["DT_EnvWind=>m_flStartTime"] = 2524
  gNetvars["DT_SlideshowDisplay=>m_szSlideshowDirectory"] = 2649
  gNetvars["DT_RopeKeyframe=>m_bConstrainBetweenEndpoints"] = 3408
  gNetvars["DT_CSPlayer=>m_iMatchStats_MoneySaved"] = 42444
  gNetvars["DT_DustTrail=>m_bEmit"] = 2828
  gNetvars["DT_TEClientProjectile=>m_vecVelocity"] = 28
  gNetvars["DT_VGuiScreen=>m_nOverlayMaterial"] = 2568
  gNetvars["DT_BaseTeamObjectiveResource=>m_iNumTeamMembers"] = 6940
  gNetvars["DT_Team=>m_nGGLeaderEntIndex_T"] = 2900
  gNetvars["DT_TEParticleSystem=>m_vecOrigin[2]"] = 24
  gNetvars["DT_TEKillPlayerAttachments=>m_nPlayer"] = 16
  gNetvars["DT_CSPlayerResource=>m_bombsiteCenterA"] = 5732
  gNetvars["DT_BaseEntity=>m_CollisionGroup"] = 1140
  gNetvars["DT_TEPhysicsProp=>m_angRotation[2]"] = 36
  gNetvars["DT_CSPlayerResource=>m_nEndMatchNextMapVotes"] = 27272
  gNetvars["CustomTable=>Dormancy"] = 0xED
